editSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/tinymce/tinymce.min.js
    - /psAdminThemePlugin/js/modules/ps_fee_news_letters.js    

newSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/tinymce/tinymce.min.js
    - /psAdminThemePlugin/js/modules/ps_fee_news_letters.js