generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsFeeReceivableStudent
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_fee_receivable_student
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _detail:  ~
        _edit: {credentials: PS_FEE_REPORT_EDIT}
        _delete: {credentials: PS_FEE_REPORT_DELETE,confirm: "Are you sure?"}
      fields:  ~
      list:    ~
      filter:  ~
      form:
        fields:
          spent_number: {help: Number user receipt}
      edit:
        display:
          Fee receipt student infomation: [ps_fee_receipt_id,student_id,title,amount,spent_number,note]
        actions:
          _cancel: ~
          _save: {credentials: [[PS_FEE_REPORT_ADD,PS_FEE_REPORT_EDIT]]}
          _delete: {credentials: PS_FEE_REPORT_DELETE}
      new:
        display:
          Fee receipt student infomation: [ps_fee_receipt_id,student_id,title,amount,spent_number,note]
        actions:
          _cancel: ~
          _save: {credentials: [[PS_FEE_REPORT_ADD,PS_FEE_REPORT_EDIT]]}
