# http://www.symfony-project.org/reference/1_4/en/13-View

editSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/modules/student.js: {position: last}
 
newSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/modules/student.js: {position: last}  