generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsEvaluateIndexCriteria
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_evaluate_index_criteria
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [school_name,criteria_code,title,subject_title,is_activated,iorder,updated_by]
        table_method: doSelectQuery
        max_per_page: 35
        actions:
          _new: {credentials: PS_EVALUATE_INDEX_CRITERIA_ADD}
        object_actions:
          _edit: {credentials: PS_EVALUATE_INDEX_CRITERIA_EDIT}
          _delete: {credentials: PS_EVALUATE_INDEX_CRITERIA_DELETE,confirm: "Are you sure?"}
        batch_actions:
         _delete: {credentials: PS_EVALUATE_INDEX_CRITERIA_DELETE,confirm: "Are you sure?"}
      filter:
        display: [school_year_id,ps_customer_id,ps_workplace_id,evaluate_subject_id,is_activated,keywords]
      form:
        display: [ps_customer_id,ps_workplace_id,evaluate_subject_id,criteria_code,title,iorder,is_activated]
      edit:  ~
      new:  ~
