generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsMemberWorkingTime
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_member_working_time
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: []
      list: []
      filter:
        display: [ps_customer_id,ps_workplace_id,start_at,stop_at,keywords]
      form:    ~
      edit:
        actions:
          _save: {credentials: PS_HR_HR_EDIT}          
          _cancel: ~
          _delete: {credentials: PS_HR_HR_DELETE,confirm: "Are you sure you want to delete this item?"}
        display: [ps_member_id,ps_workingtime_id,start_at,stop_at,note] 
      new:
        actions:
          _save: {credentials: PS_HR_HR_EDIT}          
          _cancel: ~
        display: [ps_member_id,ps_workingtime_id,start_at,stop_at,note]
