<?php

/**
 * BasePsTargetGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_customer_id
 * @property integer $ps_workplace_id
 * @property string $title
 * @property integer $note
 * @property boolean $status
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * 
 * @method integer       getPsCustomerId()    Returns the current record's "ps_customer_id" value
 * @method integer       getPsWorkplaceId()   Returns the current record's "ps_workplace_id" value
 * @method string        getTitle()           Returns the current record's "title" value
 * @method integer       getNote()            Returns the current record's "note" value
 * @method boolean       getStatus()          Returns the current record's "status" value
 * @method integer       getUserCreatedId()   Returns the current record's "user_created_id" value
 * @method integer       getUserUpdatedId()   Returns the current record's "user_updated_id" value
 * @method PsTargetGroup setPsCustomerId()    Sets the current record's "ps_customer_id" value
 * @method PsTargetGroup setPsWorkplaceId()   Sets the current record's "ps_workplace_id" value
 * @method PsTargetGroup setTitle()           Sets the current record's "title" value
 * @method PsTargetGroup setNote()            Sets the current record's "note" value
 * @method PsTargetGroup setStatus()          Sets the current record's "status" value
 * @method PsTargetGroup setUserCreatedId()   Sets the current record's "user_created_id" value
 * @method PsTargetGroup setUserUpdatedId()   Sets the current record's "user_updated_id" value
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsTargetGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_target_group');
        $this->hasColumn('ps_customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ps_workplace_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('note', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8mb4_unicode_ci');
        $this->option('charset', 'utf8mb4');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $this->hasOne('PsCustomer', array(
             'local' => 'ps_customer_id',
             'foreign' => 'id'));

        $this->hasOne('PsWorkPlaces', array(
             'local' => 'ps_workplace_id',
             'foreign' => 'id'));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}