<?php

/**
 * BasePsFeatureBranchTimeMyClass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_feature_branch_time_id
 * @property integer $ps_myclass_id
 * @property string $ps_class_room
 * @property string $note
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property FeatureBranchTimes $FeatureBranchTimes
 * @property MyClass $MyClass
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * 
 * @method integer                    getPsFeatureBranchTimeId()     Returns the current record's "ps_feature_branch_time_id" value
 * @method integer                    getPsMyclassId()               Returns the current record's "ps_myclass_id" value
 * @method string                     getPsClassRoom()               Returns the current record's "ps_class_room" value
 * @method string                     getNote()                      Returns the current record's "note" value
 * @method integer                    getUserCreatedId()             Returns the current record's "user_created_id" value
 * @method integer                    getUserUpdatedId()             Returns the current record's "user_updated_id" value
 * @method FeatureBranchTimes         getFeatureBranchTimes()        Returns the current record's "FeatureBranchTimes" value
 * @method MyClass                    getMyClass()                   Returns the current record's "MyClass" value
 * @method sfGuardUser                getUserCreated()               Returns the current record's "UserCreated" value
 * @method sfGuardUser                getUserUpdated()               Returns the current record's "UserUpdated" value
 * @method PsFeatureBranchTimeMyClass setPsFeatureBranchTimeId()     Sets the current record's "ps_feature_branch_time_id" value
 * @method PsFeatureBranchTimeMyClass setPsMyclassId()               Sets the current record's "ps_myclass_id" value
 * @method PsFeatureBranchTimeMyClass setPsClassRoom()               Sets the current record's "ps_class_room" value
 * @method PsFeatureBranchTimeMyClass setNote()                      Sets the current record's "note" value
 * @method PsFeatureBranchTimeMyClass setUserCreatedId()             Sets the current record's "user_created_id" value
 * @method PsFeatureBranchTimeMyClass setUserUpdatedId()             Sets the current record's "user_updated_id" value
 * @method PsFeatureBranchTimeMyClass setFeatureBranchTimes()        Sets the current record's "FeatureBranchTimes" value
 * @method PsFeatureBranchTimeMyClass setMyClass()                   Sets the current record's "MyClass" value
 * @method PsFeatureBranchTimeMyClass setUserCreated()               Sets the current record's "UserCreated" value
 * @method PsFeatureBranchTimeMyClass setUserUpdated()               Sets the current record's "UserUpdated" value
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsFeatureBranchTimeMyClass extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_feature_branch_time_my_class');
        $this->hasColumn('ps_feature_branch_time_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ps_myclass_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ps_class_room', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('note', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FeatureBranchTimes', array(
             'local' => 'ps_feature_branch_time_id',
             'foreign' => 'id'));

        $this->hasOne('MyClass', array(
             'local' => 'ps_myclass_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}