<?php

/**
 * BasePsCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_ward_id
 * @property string $school_code
 * @property string $school_name
 * @property string $title
 * @property string $address
 * @property string $tel
 * @property string $fax
 * @property string $mobile
 * @property string $email
 * @property string $url
 * @property integer $ps_typeschool_id
 * @property integer $is_root
 * @property string $agent
 * @property string $principal
 * @property string $note
 * @property string $description
 * @property integer $iorder
 * @property integer $is_activated
 * @property integer $is_deploy
 * @property string $logo
 * @property timestamp $activated_at
 * @property integer $year_data
 * @property string $cache_data
 * @property integer $user_activated_id
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property PsWard $PsWard
 * @property PsTypeSchool $PsTypeSchool
 * @property sfGuardUser $UserActivated
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * @property Doctrine_Collection $PsCustomers
 * @property Doctrine_Collection $PsFunction
 * @property Doctrine_Collection $PsProfessional
 * @property Doctrine_Collection $PsDepartment
 * @property Doctrine_Collection $PsUserCustomers
 * @property Doctrine_Collection $PsWorkPlaces
 * @property Doctrine_Collection $PsImages
 * 
 * @method integer             getPsWardId()          Returns the current record's "ps_ward_id" value
 * @method string              getSchoolCode()        Returns the current record's "school_code" value
 * @method string              getSchoolName()        Returns the current record's "school_name" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getAddress()           Returns the current record's "address" value
 * @method string              getTel()               Returns the current record's "tel" value
 * @method string              getFax()               Returns the current record's "fax" value
 * @method string              getMobile()            Returns the current record's "mobile" value
 * @method string              getEmail()             Returns the current record's "email" value
 * @method string              getUrl()               Returns the current record's "url" value
 * @method integer             getPsTypeschoolId()    Returns the current record's "ps_typeschool_id" value
 * @method integer             getIsRoot()            Returns the current record's "is_root" value
 * @method string              getAgent()             Returns the current record's "agent" value
 * @method string              getPrincipal()         Returns the current record's "principal" value
 * @method string              getNote()              Returns the current record's "note" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method integer             getIorder()            Returns the current record's "iorder" value
 * @method integer             getIsActivated()       Returns the current record's "is_activated" value
 * @method integer             getIsDeploy()          Returns the current record's "is_deploy" value
 * @method string              getLogo()              Returns the current record's "logo" value
 * @method timestamp           getActivatedAt()       Returns the current record's "activated_at" value
 * @method integer             getYearData()          Returns the current record's "year_data" value
 * @method string              getCacheData()         Returns the current record's "cache_data" value
 * @method integer             getUserActivatedId()   Returns the current record's "user_activated_id" value
 * @method integer             getUserCreatedId()     Returns the current record's "user_created_id" value
 * @method integer             getUserUpdatedId()     Returns the current record's "user_updated_id" value
 * @method PsWard              getPsWard()            Returns the current record's "PsWard" value
 * @method PsTypeSchool        getPsTypeSchool()      Returns the current record's "PsTypeSchool" value
 * @method sfGuardUser         getUserActivated()     Returns the current record's "UserActivated" value
 * @method sfGuardUser         getUserCreated()       Returns the current record's "UserCreated" value
 * @method sfGuardUser         getUserUpdated()       Returns the current record's "UserUpdated" value
 * @method Doctrine_Collection getPsCustomers()       Returns the current record's "PsCustomers" collection
 * @method Doctrine_Collection getPsFunction()        Returns the current record's "PsFunction" collection
 * @method Doctrine_Collection getPsProfessional()    Returns the current record's "PsProfessional" collection
 * @method Doctrine_Collection getPsDepartment()      Returns the current record's "PsDepartment" collection
 * @method Doctrine_Collection getPsUserCustomers()   Returns the current record's "PsUserCustomers" collection
 * @method Doctrine_Collection getPsWorkPlaces()      Returns the current record's "PsWorkPlaces" collection
 * @method Doctrine_Collection getPsImages()          Returns the current record's "PsImages" collection
 * @method PsCustomer          setPsWardId()          Sets the current record's "ps_ward_id" value
 * @method PsCustomer          setSchoolCode()        Sets the current record's "school_code" value
 * @method PsCustomer          setSchoolName()        Sets the current record's "school_name" value
 * @method PsCustomer          setTitle()             Sets the current record's "title" value
 * @method PsCustomer          setAddress()           Sets the current record's "address" value
 * @method PsCustomer          setTel()               Sets the current record's "tel" value
 * @method PsCustomer          setFax()               Sets the current record's "fax" value
 * @method PsCustomer          setMobile()            Sets the current record's "mobile" value
 * @method PsCustomer          setEmail()             Sets the current record's "email" value
 * @method PsCustomer          setUrl()               Sets the current record's "url" value
 * @method PsCustomer          setPsTypeschoolId()    Sets the current record's "ps_typeschool_id" value
 * @method PsCustomer          setIsRoot()            Sets the current record's "is_root" value
 * @method PsCustomer          setAgent()             Sets the current record's "agent" value
 * @method PsCustomer          setPrincipal()         Sets the current record's "principal" value
 * @method PsCustomer          setNote()              Sets the current record's "note" value
 * @method PsCustomer          setDescription()       Sets the current record's "description" value
 * @method PsCustomer          setIorder()            Sets the current record's "iorder" value
 * @method PsCustomer          setIsActivated()       Sets the current record's "is_activated" value
 * @method PsCustomer          setIsDeploy()          Sets the current record's "is_deploy" value
 * @method PsCustomer          setLogo()              Sets the current record's "logo" value
 * @method PsCustomer          setActivatedAt()       Sets the current record's "activated_at" value
 * @method PsCustomer          setYearData()          Sets the current record's "year_data" value
 * @method PsCustomer          setCacheData()         Sets the current record's "cache_data" value
 * @method PsCustomer          setUserActivatedId()   Sets the current record's "user_activated_id" value
 * @method PsCustomer          setUserCreatedId()     Sets the current record's "user_created_id" value
 * @method PsCustomer          setUserUpdatedId()     Sets the current record's "user_updated_id" value
 * @method PsCustomer          setPsWard()            Sets the current record's "PsWard" value
 * @method PsCustomer          setPsTypeSchool()      Sets the current record's "PsTypeSchool" value
 * @method PsCustomer          setUserActivated()     Sets the current record's "UserActivated" value
 * @method PsCustomer          setUserCreated()       Sets the current record's "UserCreated" value
 * @method PsCustomer          setUserUpdated()       Sets the current record's "UserUpdated" value
 * @method PsCustomer          setPsCustomers()       Sets the current record's "PsCustomers" collection
 * @method PsCustomer          setPsFunction()        Sets the current record's "PsFunction" collection
 * @method PsCustomer          setPsProfessional()    Sets the current record's "PsProfessional" collection
 * @method PsCustomer          setPsDepartment()      Sets the current record's "PsDepartment" collection
 * @method PsCustomer          setPsUserCustomers()   Sets the current record's "PsUserCustomers" collection
 * @method PsCustomer          setPsWorkPlaces()      Sets the current record's "PsWorkPlaces" collection
 * @method PsCustomer          setPsImages()          Sets the current record's "PsImages" collection
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsCustomer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_customer');
        $this->hasColumn('ps_ward_id', 'integer', null, array(
             'type' => 'integer',
             'unique' => false,
             'notnull' => true,
             ));
        $this->hasColumn('school_code', 'string', 15, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => false,
             'length' => 15,
             ));
        $this->hasColumn('school_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tel', 'string', 30, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 30,
             ));
        $this->hasColumn('fax', 'string', 30, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 30,
             ));
        $this->hasColumn('mobile', 'string', 30, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 30,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'unique' => false,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ps_typeschool_id', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('is_root', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('agent', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('principal', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('iorder', 'integer', 11, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('is_activated', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('is_deploy', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('activated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('year_data', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cache_data', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('user_activated_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('school_code_idx', array(
             'fields' => 
             array(
              0 => 'school_code',
             ),
             ));
        $this->index('school_name_idx', array(
             'fields' => 
             array(
              0 => 'school_name',
             ),
             ));
        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PsWard', array(
             'local' => 'ps_ward_id',
             'foreign' => 'id'));

        $this->hasOne('PsTypeSchool', array(
             'local' => 'ps_typeschool_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserActivated', array(
             'local' => 'user_activated_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardGroup as PsCustomers', array(
             'local' => 'id',
             'foreign' => 'ps_customer_id'));

        $this->hasMany('PsFunction', array(
             'local' => 'id',
             'foreign' => 'ps_customer_id'));

        $this->hasMany('PsProfessional', array(
             'local' => 'id',
             'foreign' => 'ps_customer_id'));

        $this->hasMany('PsDepartment', array(
             'local' => 'id',
             'foreign' => 'ps_customer_id'));

        $this->hasMany('PsUserCustomers', array(
             'local' => 'id',
             'foreign' => 'ps_customer_id'));

        $this->hasMany('PsWorkPlaces', array(
             'local' => 'id',
             'foreign' => 'ps_customer_id'));

        $this->hasMany('PsImages', array(
             'local' => 'id',
             'foreign' => 'ps_customer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}