<?php

/**
 * BasePsEvaluateSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_customer_id
 * @property integer $ps_workplace_id
 * @property integer $school_year_id
 * @property string $title
 * @property string $subject_code
 * @property boolean $is_activated
 * @property integer $iorder
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property PsCustomer $PsCustomer
 * @property PsWorkPlaces $PsWorkPlaces
 * @property PsSchoolYear $PsSchoolYear
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * @property Doctrine_Collection $PsEvaluateIndexCriteria
 * 
 * @method integer             getPsCustomerId()            Returns the current record's "ps_customer_id" value
 * @method integer             getPsWorkplaceId()           Returns the current record's "ps_workplace_id" value
 * @method integer             getSchoolYearId()            Returns the current record's "school_year_id" value
 * @method string              getTitle()                   Returns the current record's "title" value
 * @method string              getSubjectCode()             Returns the current record's "subject_code" value
 * @method boolean             getIsActivated()             Returns the current record's "is_activated" value
 * @method integer             getIorder()                  Returns the current record's "iorder" value
 * @method integer             getUserCreatedId()           Returns the current record's "user_created_id" value
 * @method integer             getUserUpdatedId()           Returns the current record's "user_updated_id" value
 * @method PsCustomer          getPsCustomer()              Returns the current record's "PsCustomer" value
 * @method PsWorkPlaces        getPsWorkPlaces()            Returns the current record's "PsWorkPlaces" value
 * @method PsSchoolYear        getPsSchoolYear()            Returns the current record's "PsSchoolYear" value
 * @method sfGuardUser         getUserCreated()             Returns the current record's "UserCreated" value
 * @method sfGuardUser         getUserUpdated()             Returns the current record's "UserUpdated" value
 * @method Doctrine_Collection getPsEvaluateIndexCriteria() Returns the current record's "PsEvaluateIndexCriteria" collection
 * @method PsEvaluateSubject   setPsCustomerId()            Sets the current record's "ps_customer_id" value
 * @method PsEvaluateSubject   setPsWorkplaceId()           Sets the current record's "ps_workplace_id" value
 * @method PsEvaluateSubject   setSchoolYearId()            Sets the current record's "school_year_id" value
 * @method PsEvaluateSubject   setTitle()                   Sets the current record's "title" value
 * @method PsEvaluateSubject   setSubjectCode()             Sets the current record's "subject_code" value
 * @method PsEvaluateSubject   setIsActivated()             Sets the current record's "is_activated" value
 * @method PsEvaluateSubject   setIorder()                  Sets the current record's "iorder" value
 * @method PsEvaluateSubject   setUserCreatedId()           Sets the current record's "user_created_id" value
 * @method PsEvaluateSubject   setUserUpdatedId()           Sets the current record's "user_updated_id" value
 * @method PsEvaluateSubject   setPsCustomer()              Sets the current record's "PsCustomer" value
 * @method PsEvaluateSubject   setPsWorkPlaces()            Sets the current record's "PsWorkPlaces" value
 * @method PsEvaluateSubject   setPsSchoolYear()            Sets the current record's "PsSchoolYear" value
 * @method PsEvaluateSubject   setUserCreated()             Sets the current record's "UserCreated" value
 * @method PsEvaluateSubject   setUserUpdated()             Sets the current record's "UserUpdated" value
 * @method PsEvaluateSubject   setPsEvaluateIndexCriteria() Sets the current record's "PsEvaluateIndexCriteria" collection
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsEvaluateSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_evaluate_subject');
        $this->hasColumn('ps_customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ps_workplace_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('school_year_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subject_code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 0,
             'length' => 255,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('iorder', 'integer', 11, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 11,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PsCustomer', array(
             'local' => 'ps_customer_id',
             'foreign' => 'id'));

        $this->hasOne('PsWorkPlaces', array(
             'local' => 'ps_workplace_id',
             'foreign' => 'id'));

        $this->hasOne('PsSchoolYear', array(
             'local' => 'school_year_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $this->hasMany('PsEvaluateIndexCriteria', array(
             'local' => 'id',
             'foreign' => 'evaluate_subject_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}