<?php

/**
 * BasePsAppPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $ps_app_id
 * @property string $app_permission_code
 * @property string $description
 * @property integer $iorder
 * @property boolean $is_system
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property Doctrine_Collection $PsApp
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * @property sfGuardPermission $PsAppPermissions
 * 
 * @method string              getTitle()               Returns the current record's "title" value
 * @method integer             getPsAppId()             Returns the current record's "ps_app_id" value
 * @method string              getAppPermissionCode()   Returns the current record's "app_permission_code" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getIorder()              Returns the current record's "iorder" value
 * @method boolean             getIsSystem()            Returns the current record's "is_system" value
 * @method integer             getUserCreatedId()       Returns the current record's "user_created_id" value
 * @method integer             getUserUpdatedId()       Returns the current record's "user_updated_id" value
 * @method Doctrine_Collection getPsApp()               Returns the current record's "PsApp" collection
 * @method sfGuardUser         getUserCreated()         Returns the current record's "UserCreated" value
 * @method sfGuardUser         getUserUpdated()         Returns the current record's "UserUpdated" value
 * @method sfGuardPermission   getPsAppPermissions()    Returns the current record's "PsAppPermissions" value
 * @method PsAppPermission     setTitle()               Sets the current record's "title" value
 * @method PsAppPermission     setPsAppId()             Sets the current record's "ps_app_id" value
 * @method PsAppPermission     setAppPermissionCode()   Sets the current record's "app_permission_code" value
 * @method PsAppPermission     setDescription()         Sets the current record's "description" value
 * @method PsAppPermission     setIorder()              Sets the current record's "iorder" value
 * @method PsAppPermission     setIsSystem()            Sets the current record's "is_system" value
 * @method PsAppPermission     setUserCreatedId()       Sets the current record's "user_created_id" value
 * @method PsAppPermission     setUserUpdatedId()       Sets the current record's "user_updated_id" value
 * @method PsAppPermission     setPsApp()               Sets the current record's "PsApp" collection
 * @method PsAppPermission     setUserCreated()         Sets the current record's "UserCreated" value
 * @method PsAppPermission     setUserUpdated()         Sets the current record's "UserUpdated" value
 * @method PsAppPermission     setPsAppPermissions()    Sets the current record's "PsAppPermissions" value
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsAppPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_app_permission');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ps_app_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('app_permission_code', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('iorder', 'integer', 11, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('is_system', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PsApp', array(
             'local' => 'ps_app_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardPermission as PsAppPermissions', array(
             'local' => 'id',
             'foreign' => 'ps_app_permission_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}