<?php

/**
 * BasePsSymbol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_customer_id
 * @property integer $ps_workplace_id
 * @property string $title
 * @property string $note
 * @property boolean $is_type
 * @property integer $service_id
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * 
 * @method integer  get()                Returns the current record's "ps_customer_id" value
 * @method integer  get()                Returns the current record's "ps_workplace_id" value
 * @method string   get()                Returns the current record's "title" value
 * @method string   get()                Returns the current record's "note" value
 * @method boolean  get()                Returns the current record's "is_type" value
 * @method integer  get()                Returns the current record's "service_id" value
 * @method integer  get()                Returns the current record's "user_created_id" value
 * @method integer  get()                Returns the current record's "user_updated_id" value
 * @method PsSymbol set()                Sets the current record's "ps_customer_id" value
 * @method PsSymbol set()                Sets the current record's "ps_workplace_id" value
 * @method PsSymbol set()                Sets the current record's "title" value
 * @method PsSymbol set()                Sets the current record's "note" value
 * @method PsSymbol set()                Sets the current record's "is_type" value
 * @method PsSymbol set()                Sets the current record's "service_id" value
 * @method PsSymbol set()                Sets the current record's "user_created_id" value
 * @method PsSymbol set()                Sets the current record's "user_updated_id" value
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsSymbol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_symbol');
        $this->hasColumn('ps_customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ps_workplace_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_type', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('service_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8mb4_unicode_ci');
        $this->option('charset', 'utf8mb4');
    }


    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $this->hasOne('PsCustomer', array(
             'local' => 'ps_customer_id',
             'foreign' => 'id'));

        $this->hasOne('PsWorkPlaces', array(
             'local' => 'ps_workplace_id',
             'foreign' => 'id'));

        $this->hasOne('Service', array(
             'local' => 'service_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}