<?php

/**
 * BaseFeature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_customer_id
 * @property string $name
 * @property integer $ps_image_id
 * @property integer $ps_obj_group_id
 * @property string $note
 * @property string $description
 * @property integer $iorder
 * @property boolean $is_activated
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property PsObjectGroups $PsObjectGroups
 * @property Doctrine_Collection $FeatureBranch
 * @property PsImages $PsImages
 * @property PsCustomer $PsCustomer
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * @property Doctrine_Collection $FeatureOption
 * 
 * @method integer             getPsCustomerId()    Returns the current record's "ps_customer_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method integer             getPsImageId()       Returns the current record's "ps_image_id" value
 * @method integer             getPsObjGroupId()    Returns the current record's "ps_obj_group_id" value
 * @method string              getNote()            Returns the current record's "note" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method integer             getIorder()          Returns the current record's "iorder" value
 * @method boolean             getIsActivated()     Returns the current record's "is_activated" value
 * @method integer             getUserCreatedId()   Returns the current record's "user_created_id" value
 * @method integer             getUserUpdatedId()   Returns the current record's "user_updated_id" value
 * @method PsObjectGroups      getPsObjectGroups()  Returns the current record's "PsObjectGroups" value
 * @method Doctrine_Collection getFeatureBranch()   Returns the current record's "FeatureBranch" collection
 * @method PsImages            getPsImages()        Returns the current record's "PsImages" value
 * @method PsCustomer          getPsCustomer()      Returns the current record's "PsCustomer" value
 * @method sfGuardUser         getUserCreated()     Returns the current record's "UserCreated" value
 * @method sfGuardUser         getUserUpdated()     Returns the current record's "UserUpdated" value
 * @method Doctrine_Collection getFeatureOption()   Returns the current record's "FeatureOption" collection
 * @method Feature             setPsCustomerId()    Sets the current record's "ps_customer_id" value
 * @method Feature             setName()            Sets the current record's "name" value
 * @method Feature             setPsImageId()       Sets the current record's "ps_image_id" value
 * @method Feature             setPsObjGroupId()    Sets the current record's "ps_obj_group_id" value
 * @method Feature             setNote()            Sets the current record's "note" value
 * @method Feature             setDescription()     Sets the current record's "description" value
 * @method Feature             setIorder()          Sets the current record's "iorder" value
 * @method Feature             setIsActivated()     Sets the current record's "is_activated" value
 * @method Feature             setUserCreatedId()   Sets the current record's "user_created_id" value
 * @method Feature             setUserUpdatedId()   Sets the current record's "user_updated_id" value
 * @method Feature             setPsObjectGroups()  Sets the current record's "PsObjectGroups" value
 * @method Feature             setFeatureBranch()   Sets the current record's "FeatureBranch" collection
 * @method Feature             setPsImages()        Sets the current record's "PsImages" value
 * @method Feature             setPsCustomer()      Sets the current record's "PsCustomer" value
 * @method Feature             setUserCreated()     Sets the current record's "UserCreated" value
 * @method Feature             setUserUpdated()     Sets the current record's "UserUpdated" value
 * @method Feature             setFeatureOption()   Sets the current record's "FeatureOption" collection
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeature extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feature');
        $this->hasColumn('ps_customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ps_image_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ps_obj_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('iorder', 'integer', 11, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 11,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PsObjectGroups', array(
             'local' => 'ps_obj_group_id',
             'foreign' => 'id'));

        $this->hasMany('FeatureBranch', array(
             'local' => 'id',
             'foreign' => 'feature_id'));

        $this->hasOne('PsImages', array(
             'local' => 'ps_image_id',
             'foreign' => 'id'));

        $this->hasOne('PsCustomer', array(
             'local' => 'ps_customer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $this->hasMany('FeatureOption', array(
             'local' => 'id',
             'foreign' => 'feature_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}