<?php

/**
 * BasePsFeatureBranchMyClass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_feature_branch_id
 * @property integer $ps_myclass_id
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property FeatureBranch $FeatureBranch
 * @property MyClass $MyClass
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * 
 * @method integer                getPsFeatureBranchId()    Returns the current record's "ps_feature_branch_id" value
 * @method integer                getPsMyclassId()          Returns the current record's "ps_myclass_id" value
 * @method integer                getUserCreatedId()        Returns the current record's "user_created_id" value
 * @method integer                getUserUpdatedId()        Returns the current record's "user_updated_id" value
 * @method FeatureBranch          getFeatureBranch()        Returns the current record's "FeatureBranch" value
 * @method MyClass                getMyClass()              Returns the current record's "MyClass" value
 * @method sfGuardUser            getUserCreated()          Returns the current record's "UserCreated" value
 * @method sfGuardUser            getUserUpdated()          Returns the current record's "UserUpdated" value
 * @method PsFeatureBranchMyClass setPsFeatureBranchId()    Sets the current record's "ps_feature_branch_id" value
 * @method PsFeatureBranchMyClass setPsMyclassId()          Sets the current record's "ps_myclass_id" value
 * @method PsFeatureBranchMyClass setUserCreatedId()        Sets the current record's "user_created_id" value
 * @method PsFeatureBranchMyClass setUserUpdatedId()        Sets the current record's "user_updated_id" value
 * @method PsFeatureBranchMyClass setFeatureBranch()        Sets the current record's "FeatureBranch" value
 * @method PsFeatureBranchMyClass setMyClass()              Sets the current record's "MyClass" value
 * @method PsFeatureBranchMyClass setUserCreated()          Sets the current record's "UserCreated" value
 * @method PsFeatureBranchMyClass setUserUpdated()          Sets the current record's "UserUpdated" value
 * 
 * @package    kidsschool.vn
 * @subpackage model
 * @author     kidsschool.vn <contact@kidsschool.vn - ntsc279@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsFeatureBranchMyClass extends sfDoctrineRecord {

	public function setTableDefinition() {

		$this->setTableName ( 'ps_feature_branch_my_class' );
		$this->hasColumn ( 'ps_feature_branch_id', 'integer', null, array (
				'type' => 'integer' ) );
		$this->hasColumn ( 'ps_myclass_id', 'integer', null, array (
				'type' => 'integer' ) );
		$this->hasColumn ( 'user_created_id', 'integer', null, array (
				'type' => 'integer' ) );
		$this->hasColumn ( 'user_updated_id', 'integer', null, array (
				'type' => 'integer' ) );

		$this->option ( 'type', 'InnoDB' );
		$this->option ( 'collate', 'utf8_unicode_ci' );
		$this->option ( 'charset', 'utf8' );
	}

	public function setUp() {

		parent::setUp ();
		$this->hasOne ( 'FeatureBranch', array (
				'local' => 'ps_feature_branch_id',
				'foreign' => 'id' ) );

		$this->hasOne ( 'MyClass', array (
				'local' => 'ps_myclass_id',
				'foreign' => 'id',
				'onDelete' => 'CASCADE' ) );

		$this->hasOne ( 'sfGuardUser as UserCreated', array (
				'local' => 'user_created_id',
				'foreign' => 'id' ) );

		$this->hasOne ( 'sfGuardUser as UserUpdated', array (
				'local' => 'user_updated_id',
				'foreign' => 'id' ) );

		$timestampable0 = new Doctrine_Template_Timestampable ();
		$this->actAs ( $timestampable0 );
	}
}