<?php

/**
 * BaseStudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_customer_id
 * @property integer $ps_workplace_id
 * @property string $student_code
 * @property string $first_name
 * @property string $last_name
 * @property boolean $sex
 * @property datetime $birthday
 * @property string $common_name
 * @property string $nick_name
 * @property string $image
 * @property string $avatar
 * @property integer $ethnic_id
 * @property integer $religion_id
 * @property string $nationality
 * @property string $address
 * @property string $status
 * @property integer $year_data
 * @property timestamp $deleted_at
 * @property timestamp $start_date_at
 * @property boolean $is_import
 * @property integer $current_class_id
 * @property json $attributes
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property PsStudentGrowths $PsStudentGrowths
 * @property StudentClass $StudentClass
 * @property PsLogtimes $PsLogtimes
 * @property ReceivableStudent $ReceivableStudent
 * @property CollectedStudent $CollectedStudent
 * @property StudentServiceDiary $StudentServiceDiary
 * @property StudentFeature $StudentFeature
 * @property StudentService $StudentService
 * @property Receipt $Receipt
 * @property PsFeeReports $PsFeeReports
 * @property StudentServiceCourseComment $StudentServiceCourseComment
 * @property PsServiceSaturday $PsServiceSaturday
 * @property PsEvaluateSemester $PsEvaluateSemester
 * @property PsCommentWeek $PsCommentWeek
 * @property MyClass $MyClass
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * @property PsCustomer $PsCustomer
 * @property PsWorkPlaces $PsWorkPlaces
 * @property PsEthnic $PsEthnic
 * @property PsReligion $PsReligion
 * @property Doctrine_Collection $Students
 * @property Doctrine_Collection $PsAdvices
 * @property Doctrine_Collection $PsEvaluateIndexStudent
 * @property Doctrine_Collection $PsEvaluateSemesterStudent
 * 
 * @method integer                     getPsCustomerId()                Returns the current record's "ps_customer_id" value
 * @method integer                     getPsWorkplaceId()               Returns the current record's "ps_workplace_id" value
 * @method string                      getStudentCode()                 Returns the current record's "student_code" value
 * @method string                      getFirstName()                   Returns the current record's "first_name" value
 * @method string                      getLastName()                    Returns the current record's "last_name" value
 * @method boolean                     getSex()                         Returns the current record's "sex" value
 * @method datetime                    getBirthday()                    Returns the current record's "birthday" value
 * @method string                      getCommonName()                  Returns the current record's "common_name" value
 * @method string                      getNickName()                    Returns the current record's "nick_name" value
 * @method string                      getImage()                       Returns the current record's "image" value
 * @method string                      getAvatar()                      Returns the current record's "avatar" value
 * @method integer                     getEthnicId()                    Returns the current record's "ethnic_id" value
 * @method integer                     getReligionId()                  Returns the current record's "religion_id" value
 * @method string                      getNationality()                 Returns the current record's "nationality" value
 * @method string                      getAddress()                     Returns the current record's "address" value
 * @method string                      getStatus()                      Returns the current record's "status" value
 * @method integer                     getYearData()                    Returns the current record's "year_data" value
 * @method timestamp                   getDeletedAt()                   Returns the current record's "deleted_at" value
 * @method timestamp                   getStartDateAt()                 Returns the current record's "start_date_at" value
 * @method boolean                     getIsImport()                    Returns the current record's "is_import" value
 * @method integer                     getCurrentClassId()              Returns the current record's "current_class_id" value
 * @method json                        getAttributes()                  Returns the current record's "attributes" value
 * @method integer                     getUserCreatedId()               Returns the current record's "user_created_id" value
 * @method integer                     getUserUpdatedId()               Returns the current record's "user_updated_id" value
 * @method PsStudentGrowths            getPsStudentGrowths()            Returns the current record's "PsStudentGrowths" value
 * @method StudentClass                getStudentClass()                Returns the current record's "StudentClass" value
 * @method PsLogtimes                  getPsLogtimes()                  Returns the current record's "PsLogtimes" value
 * @method ReceivableStudent           getReceivableStudent()           Returns the current record's "ReceivableStudent" value
 * @method CollectedStudent            getCollectedStudent()            Returns the current record's "CollectedStudent" value
 * @method StudentServiceDiary         getStudentServiceDiary()         Returns the current record's "StudentServiceDiary" value
 * @method StudentFeature              getStudentFeature()              Returns the current record's "StudentFeature" value
 * @method StudentService              getStudentService()              Returns the current record's "StudentService" value
 * @method Receipt                     getReceipt()                     Returns the current record's "Receipt" value
 * @method PsFeeReports                getPsFeeReports()                Returns the current record's "PsFeeReports" value
 * @method StudentServiceCourseComment getStudentServiceCourseComment() Returns the current record's "StudentServiceCourseComment" value
 * @method PsServiceSaturday           getPsServiceSaturday()           Returns the current record's "PsServiceSaturday" value
 * @method PsEvaluateSemester          getPsEvaluateSemester()          Returns the current record's "PsEvaluateSemester" value
 * @method PsCommentWeek               getPsCommentWeek()               Returns the current record's "PsCommentWeek" value
 * @method MyClass                     getMyClass()                     Returns the current record's "MyClass" value
 * @method sfGuardUser                 getUserCreated()                 Returns the current record's "UserCreated" value
 * @method sfGuardUser                 getUserUpdated()                 Returns the current record's "UserUpdated" value
 * @method PsCustomer                  getPsCustomer()                  Returns the current record's "PsCustomer" value
 * @method PsWorkPlaces                getPsWorkPlaces()                Returns the current record's "PsWorkPlaces" value
 * @method PsEthnic                    getPsEthnic()                    Returns the current record's "PsEthnic" value
 * @method PsReligion                  getPsReligion()                  Returns the current record's "PsReligion" value
 * @method Doctrine_Collection         getStudents()                    Returns the current record's "Students" collection
 * @method Doctrine_Collection         getPsAdvices()                   Returns the current record's "PsAdvices" collection
 * @method Doctrine_Collection         getPsEvaluateIndexStudent()      Returns the current record's "PsEvaluateIndexStudent" collection
 * @method Doctrine_Collection         getPsEvaluateSemesterStudent()   Returns the current record's "PsEvaluateSemesterStudent" collection
 * @method Student                     setPsCustomerId()                Sets the current record's "ps_customer_id" value
 * @method Student                     setPsWorkplaceId()               Sets the current record's "ps_workplace_id" value
 * @method Student                     setStudentCode()                 Sets the current record's "student_code" value
 * @method Student                     setFirstName()                   Sets the current record's "first_name" value
 * @method Student                     setLastName()                    Sets the current record's "last_name" value
 * @method Student                     setSex()                         Sets the current record's "sex" value
 * @method Student                     setBirthday()                    Sets the current record's "birthday" value
 * @method Student                     setCommonName()                  Sets the current record's "common_name" value
 * @method Student                     setNickName()                    Sets the current record's "nick_name" value
 * @method Student                     setImage()                       Sets the current record's "image" value
 * @method Student                     setAvatar()                      Sets the current record's "avatar" value
 * @method Student                     setEthnicId()                    Sets the current record's "ethnic_id" value
 * @method Student                     setReligionId()                  Sets the current record's "religion_id" value
 * @method Student                     setNationality()                 Sets the current record's "nationality" value
 * @method Student                     setAddress()                     Sets the current record's "address" value
 * @method Student                     setStatus()                      Sets the current record's "status" value
 * @method Student                     setYearData()                    Sets the current record's "year_data" value
 * @method Student                     setDeletedAt()                   Sets the current record's "deleted_at" value
 * @method Student                     setStartDateAt()                 Sets the current record's "start_date_at" value
 * @method Student                     setIsImport()                    Sets the current record's "is_import" value
 * @method Student                     setCurrentClassId()              Sets the current record's "current_class_id" value
 * @method Student                     setAttributes()                  Sets the current record's "attributes" value
 * @method Student                     setUserCreatedId()               Sets the current record's "user_created_id" value
 * @method Student                     setUserUpdatedId()               Sets the current record's "user_updated_id" value
 * @method Student                     setPsStudentGrowths()            Sets the current record's "PsStudentGrowths" value
 * @method Student                     setStudentClass()                Sets the current record's "StudentClass" value
 * @method Student                     setPsLogtimes()                  Sets the current record's "PsLogtimes" value
 * @method Student                     setReceivableStudent()           Sets the current record's "ReceivableStudent" value
 * @method Student                     setCollectedStudent()            Sets the current record's "CollectedStudent" value
 * @method Student                     setStudentServiceDiary()         Sets the current record's "StudentServiceDiary" value
 * @method Student                     setStudentFeature()              Sets the current record's "StudentFeature" value
 * @method Student                     setStudentService()              Sets the current record's "StudentService" value
 * @method Student                     setReceipt()                     Sets the current record's "Receipt" value
 * @method Student                     setPsFeeReports()                Sets the current record's "PsFeeReports" value
 * @method Student                     setStudentServiceCourseComment() Sets the current record's "StudentServiceCourseComment" value
 * @method Student                     setPsServiceSaturday()           Sets the current record's "PsServiceSaturday" value
 * @method Student                     setPsEvaluateSemester()          Sets the current record's "PsEvaluateSemester" value
 * @method Student                     setPsCommentWeek()               Sets the current record's "PsCommentWeek" value
 * @method Student                     setMyClass()                     Sets the current record's "MyClass" value
 * @method Student                     setUserCreated()                 Sets the current record's "UserCreated" value
 * @method Student                     setUserUpdated()                 Sets the current record's "UserUpdated" value
 * @method Student                     setPsCustomer()                  Sets the current record's "PsCustomer" value
 * @method Student                     setPsWorkPlaces()                Sets the current record's "PsWorkPlaces" value
 * @method Student                     setPsEthnic()                    Sets the current record's "PsEthnic" value
 * @method Student                     setPsReligion()                  Sets the current record's "PsReligion" value
 * @method Student                     setStudents()                    Sets the current record's "Students" collection
 * @method Student                     setPsAdvices()                   Sets the current record's "PsAdvices" collection
 * @method Student                     setPsEvaluateIndexStudent()      Sets the current record's "PsEvaluateIndexStudent" collection
 * @method Student                     setPsEvaluateSemesterStudent()   Sets the current record's "PsEvaluateSemesterStudent" collection
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student');
        $this->hasColumn('ps_customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ps_workplace_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('student_code', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sex', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('birthday', 'datetime', 10, array(
             'type' => 'datetime',
             'length' => 10,
             ));
        $this->hasColumn('common_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nick_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('avatar', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ethnic_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('religion_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('nationality', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 4, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('year_data', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('number_ae', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'default' => 0,
             ));
        $this->hasColumn('type_year', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'default' => 0,
             ));
        $this->hasColumn('deleted_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('statistic_class_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('relative_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('start_date_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('is_import', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('current_class_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('policy_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('caphoc', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('chuongtrinh', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('khoihoc', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('doituong', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('attributes', 'json', null, array(
             'type' => 'json',
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('student_code_idx', array(
             'fields' => 
             array(
              0 => 'student_code',
             ),
             ));
        $this->index('first_name_idx', array(
             'fields' => 
             array(
              0 => 'first_name',
             ),
             ));
        $this->index('last_name_idx', array(
             'fields' => 
             array(
              0 => 'last_name',
             ),
             ));
        $this->index('myclass_idx', array(
             'fields' => 
             array(
              0 => 'myclass_id',
             ),
             ));
        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PsStudentGrowths', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('StudentClass', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('PsLogtimes', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('ReceivableStudent', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('CollectedStudent', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('StudentServiceDiary', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('StudentFeature', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('StudentService', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('Receipt', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('PsFeeReports', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('StudentServiceCourseComment', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('PsServiceSaturday', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('PsEvaluateSemester', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('PsCommentWeek', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasOne('MyClass', array(
             'local' => 'current_class_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $this->hasOne('PsCustomer', array(
             'local' => 'ps_customer_id',
             'foreign' => 'id'));

        $this->hasOne('PsWorkPlaces', array(
             'local' => 'ps_workplace_id',
             'foreign' => 'id'));

        $this->hasOne('PsEthnic', array(
             'local' => 'ethnic_id',
             'foreign' => 'id'));

        $this->hasOne('PsPolicyGroup', array(
             'local' => 'policy_id',
             'foreign' => 'id'));

        $this->hasOne('PsObjectGroups', array(
             'local' => 'khoihoc',
             'foreign' => 'id'));

        $this->hasOne('PsTargetGroup', array(
             'local' => 'doituong',
             'foreign' => 'id'));

        $this->hasOne('PsReligion', array(
             'local' => 'religion_id',
             'foreign' => 'id'));

        $this->hasMany('PsHistoryStudentFeatures as Students', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('PsAdvices', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('PsEvaluateIndexStudent', array(
             'local' => 'id',
             'foreign' => 'ps_student_id'));

        $this->hasMany('PsEvaluateSemesterStudent', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}