<?php

/**
 * BasePsMemberSalary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ps_member_id
 * @property integer $ps_salary_id
 * @property date $start_at
 * @property date $stop_at
 * @property integer $days_working
 * @property string $note
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property PsMember $PsMember
 * @property PsSalary $PsSalary
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * 
 * @method integer        getPsMemberId()      Returns the current record's "ps_member_id" value
 * @method integer        getPsSalaryId()      Returns the current record's "ps_salary_id" value
 * @method date           getStartAt()         Returns the current record's "start_at" value
 * @method date           getStopAt()          Returns the current record's "stop_at" value
 * @method integer        getDaysWorking()     Returns the current record's "days_working" value
 * @method string         getNote()            Returns the current record's "note" value
 * @method integer        getUserCreatedId()   Returns the current record's "user_created_id" value
 * @method integer        getUserUpdatedId()   Returns the current record's "user_updated_id" value
 * @method PsMember       getPsMember()        Returns the current record's "PsMember" value
 * @method PsSalary       getPsSalary()        Returns the current record's "PsSalary" value
 * @method sfGuardUser    getUserCreated()     Returns the current record's "UserCreated" value
 * @method sfGuardUser    getUserUpdated()     Returns the current record's "UserUpdated" value
 * @method PsMemberSalary setPsMemberId()      Sets the current record's "ps_member_id" value
 * @method PsMemberSalary setPsSalaryId()      Sets the current record's "ps_salary_id" value
 * @method PsMemberSalary setStartAt()         Sets the current record's "start_at" value
 * @method PsMemberSalary setStopAt()          Sets the current record's "stop_at" value
 * @method PsMemberSalary setDaysWorking()     Sets the current record's "days_working" value
 * @method PsMemberSalary setNote()            Sets the current record's "note" value
 * @method PsMemberSalary setUserCreatedId()   Sets the current record's "user_created_id" value
 * @method PsMemberSalary setUserUpdatedId()   Sets the current record's "user_updated_id" value
 * @method PsMemberSalary setPsMember()        Sets the current record's "PsMember" value
 * @method PsMemberSalary setPsSalary()        Sets the current record's "PsSalary" value
 * @method PsMemberSalary setUserCreated()     Sets the current record's "UserCreated" value
 * @method PsMemberSalary setUserUpdated()     Sets the current record's "UserUpdated" value
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsMemberSalary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_member_salary');
        $this->hasColumn('ps_member_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ps_salary_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('start_at', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('stop_at', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('days_working', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PsMember', array(
             'local' => 'ps_member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PsSalary', array(
             'local' => 'ps_salary_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}