<?php

/**
 * BasePsTimesheetSummarys
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property timestamp $timesheet_at
 * @property double $number_time
 * @property double $number_belated
 * @property double $number_early
 * @property string $description
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property PsMember $PsMember
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * 
 * @method integer             getMemberId()        Returns the current record's "member_id" value
 * @method timestamp           getTimesheetAt()     Returns the current record's "timesheet_at" value
 * @method double              getNumberTime()      Returns the current record's "number_time" value
 * @method double              getNumberBelated()   Returns the current record's "number_belated" value
 * @method double              getNumberEarly()     Returns the current record's "number_early" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method integer             getUserCreatedId()   Returns the current record's "user_created_id" value
 * @method integer             getUserUpdatedId()   Returns the current record's "user_updated_id" value
 * @method PsMember            getPsMember()        Returns the current record's "PsMember" value
 * @method sfGuardUser         getUserCreated()     Returns the current record's "UserCreated" value
 * @method sfGuardUser         getUserUpdated()     Returns the current record's "UserUpdated" value
 * @method PsTimesheetSummarys setMemberId()        Sets the current record's "member_id" value
 * @method PsTimesheetSummarys setTimesheetAt()     Sets the current record's "timesheet_at" value
 * @method PsTimesheetSummarys setNumberTime()      Sets the current record's "number_time" value
 * @method PsTimesheetSummarys setNumberBelated()   Sets the current record's "number_belated" value
 * @method PsTimesheetSummarys setNumberEarly()     Sets the current record's "number_early" value
 * @method PsTimesheetSummarys setDescription()     Sets the current record's "description" value
 * @method PsTimesheetSummarys setUserCreatedId()   Sets the current record's "user_created_id" value
 * @method PsTimesheetSummarys setUserUpdatedId()   Sets the current record's "user_updated_id" value
 * @method PsTimesheetSummarys setPsMember()        Sets the current record's "PsMember" value
 * @method PsTimesheetSummarys setUserCreated()     Sets the current record's "UserCreated" value
 * @method PsTimesheetSummarys setUserUpdated()     Sets the current record's "UserUpdated" value
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsTimesheetSummarys extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_timesheet_summarys');
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('timesheet_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('number_time', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('number_belated', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('number_early', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PsMember', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}