<?php

/**
 * BasePsObjectGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $note
 * @property integer $iorder
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * @property Doctrine_Collection $PsObjectGroupes
 * 
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getNote()            Returns the current record's "note" value
 * @method integer             getIorder()          Returns the current record's "iorder" value
 * @method integer             getUserCreatedId()   Returns the current record's "user_created_id" value
 * @method integer             getUserUpdatedId()   Returns the current record's "user_updated_id" value
 * @method sfGuardUser         getUserCreated()     Returns the current record's "UserCreated" value
 * @method sfGuardUser         getUserUpdated()     Returns the current record's "UserUpdated" value
 * @method Doctrine_Collection getPsObjectGroupes() Returns the current record's "PsObjectGroupes" collection
 * @method PsObjectGroup       setTitle()           Sets the current record's "title" value
 * @method PsObjectGroup       setNote()            Sets the current record's "note" value
 * @method PsObjectGroup       setIorder()          Sets the current record's "iorder" value
 * @method PsObjectGroup       setUserCreatedId()   Sets the current record's "user_created_id" value
 * @method PsObjectGroup       setUserUpdatedId()   Sets the current record's "user_updated_id" value
 * @method PsObjectGroup       setUserCreated()     Sets the current record's "UserCreated" value
 * @method PsObjectGroup       setUserUpdated()     Sets the current record's "UserUpdated" value
 * @method PsObjectGroup       setPsObjectGroupes() Sets the current record's "PsObjectGroupes" collection
 * 
 * @package    quanlymamnon.vn
 * @subpackage model
 * @author     quanlymamnon.vn <contact@quanlymamnon.vn - ntsc279@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsObjectGroup extends sfDoctrineRecord {

	public function setTableDefinition() {

		$this->setTableName ( 'ps_object_group' );
		$this->hasColumn ( 'title', 'string', 255, array (
				'type' => 'string',
				'notnull' => true,
				'length' => 255 ) );
		$this->hasColumn ( 'note', 'string', 255, array (
				'type' => 'string',
				'length' => 255 ) );
		$this->hasColumn ( 'iorder', 'integer', 11, array (
				'type' => 'integer',
				'default' => 0,
				'length' => 11 ) );
		$this->hasColumn ( 'user_created_id', 'integer', null, array (
				'type' => 'integer' ) );
		$this->hasColumn ( 'user_updated_id', 'integer', null, array (
				'type' => 'integer' ) );

		$this->option ( 'type', 'InnoDB' );
		$this->option ( 'collate', 'utf8_unicode_ci' );
		$this->option ( 'charset', 'utf8' );
	}

	public function setUp() {

		parent::setUp ();
		$this->hasOne ( 'sfGuardUser as UserCreated', array (
				'local' => 'user_created_id',
				'foreign' => 'id' ) );

		$this->hasOne ( 'sfGuardUser as UserUpdated', array (
				'local' => 'user_updated_id',
				'foreign' => 'id' ) );

		$this->hasMany ( 'Feature as PsObjectGroupes', array (
				'local' => 'id',
				'foreign' => 'ps_obj_group_id' ) );

		$timestampable0 = new Doctrine_Template_Timestampable ();
		$this->actAs ( $timestampable0 );
	}
}