<?php

/**
 * BasePsSemester
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $school_year_id
 * @property integer $ps_customer_id
 * @property integer $ps_workplace_id
 * @property string $semester_one
 * @property string $semester_two
 * @property integer $user_created_id
 * @property integer $user_updated_id
 * @property PsSchoolYear $PsSchoolYear
 * @property PsCustomer $PsCustomer
 * @property PsWorkPlaces $PsWorkPlaces
 * @property sfGuardUser $UserCreated
 * @property sfGuardUser $UserUpdated
 * 
 * @method integer      getSchoolYearId()    Returns the current record's "school_year_id" value
 * @method integer      getPsCustomerId()    Returns the current record's "ps_customer_id" value
 * @method integer      getPsWorkplaceId()   Returns the current record's "ps_workplace_id" value
 * @method string       getSemesterOne()     Returns the current record's "semester_one" value
 * @method string       getSemesterTwo()     Returns the current record's "semester_two" value
 * @method integer      getUserCreatedId()   Returns the current record's "user_created_id" value
 * @method integer      getUserUpdatedId()   Returns the current record's "user_updated_id" value
 * @method PsSchoolYear getPsSchoolYear()    Returns the current record's "PsSchoolYear" value
 * @method PsCustomer   getPsCustomer()      Returns the current record's "PsCustomer" value
 * @method PsWorkPlaces getPsWorkPlaces()    Returns the current record's "PsWorkPlaces" value
 * @method sfGuardUser  getUserCreated()     Returns the current record's "UserCreated" value
 * @method sfGuardUser  getUserUpdated()     Returns the current record's "UserUpdated" value
 * @method PsSemester   setSchoolYearId()    Sets the current record's "school_year_id" value
 * @method PsSemester   setPsCustomerId()    Sets the current record's "ps_customer_id" value
 * @method PsSemester   setPsWorkplaceId()   Sets the current record's "ps_workplace_id" value
 * @method PsSemester   setSemesterOne()     Sets the current record's "semester_one" value
 * @method PsSemester   setSemesterTwo()     Sets the current record's "semester_two" value
 * @method PsSemester   setUserCreatedId()   Sets the current record's "user_created_id" value
 * @method PsSemester   setUserUpdatedId()   Sets the current record's "user_updated_id" value
 * @method PsSemester   setPsSchoolYear()    Sets the current record's "PsSchoolYear" value
 * @method PsSemester   setPsCustomer()      Sets the current record's "PsCustomer" value
 * @method PsSemester   setPsWorkPlaces()    Sets the current record's "PsWorkPlaces" value
 * @method PsSemester   setUserCreated()     Sets the current record's "UserCreated" value
 * @method PsSemester   setUserUpdated()     Sets the current record's "UserUpdated" value
 * 
 * @package    KidsSchool.vn
 * @subpackage model
 * @author     KidsSchool.vn <contact@kidsschool.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePsSemester extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ps_semester');
        $this->hasColumn('school_year_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ps_customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ps_workplace_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester_one', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('semester_two', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('user_created_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_updated_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8mb4_unicode_ci');
        $this->option('charset', 'utf8mb4');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PsSchoolYear', array(
             'local' => 'school_year_id',
             'foreign' => 'id'));

        $this->hasOne('PsCustomer', array(
             'local' => 'ps_customer_id',
             'foreign' => 'id'));

        $this->hasOne('PsWorkPlaces', array(
             'local' => 'ps_workplace_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserCreated', array(
             'local' => 'user_created_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as UserUpdated', array(
             'local' => 'user_updated_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}