generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsBabyGift
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_baby_gift
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
      list: 
        display: 	[title, image, status, updated_by, updated_at]
        table_method: doSelectQuery
      filter: 
        display: [title, status]
      form:
        display: [title, link, image, date_at, brief, status, content]
      edit: ~
      new: ~
