generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsReligion
    theme:                 admin1
    i18n_catalogue:        messages
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_religion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit: {credentials: PS_SYSTEM_RELIGION_EDIT}
        _new: {credentials: PS_SYSTEM_RELIGION_ADD}
        _delete: {credentials: PS_SYSTEM_RELIGION_DELETE}
      fields:  
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
      list:    
        display: [=title,iorder,is_activated, updated_by,updated_at]
        sort: [iorder, asc]
        table_method: doSelectQuery
      filter:
        display: 	[title,iorder,is_activated]
      form:    ~
      edit:
        actions:
          _delete:       ~
          _list:
            credentials: [[PS_SYSTEM_RELIGION_SHOW,PS_SYSTEM_RELIGION_DETAIL,PS_SYSTEM_RELIGION_EDIT]]
          _save:
            credentials: [PS_SYSTEM_RELIGION_EDIT]
          _save_and_add:
            credentials: [PS_SYSTEM_RELIGION_EDIT,PS_SYSTEM_RELIGION_ADD]
      new:
        actions:          
          _list:
            credentials: [[PS_SYSTEM_RELIGION_SHOW,PS_SYSTEM_RELIGION_EDIT,PS_SYSTEM_RELIGION_ADD,PS_SYSTEM_RELIGION_DELETE]]
          _save:
            credentials: [PS_SYSTEM_RELIGION_ADD]
          _save_and_add:
            credentials: [PS_SYSTEM_RELIGION_ADD]
