generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsDistrict
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_district
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit: {credentials: PS_SYSTEM_DISTRICT_EDIT}
        _new: {credentials: PS_SYSTEM_DISTRICT_ADD}
        _delete: {credentials: PS_SYSTEM_DISTRICT_DELETE}
      fields:  
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
      list:    
        display: [=s_code,=name,province_name,iorder,is_activated, updated_by,updated_at]
        sort: [iorder, asc]
        table_method: doSelectQuery
        max_per_page: 50
      filter:
        display: [country_code,ps_province_id,s_code,name,is_activated]
      form:
        display: [country_code,ps_province_id,s_code,name,description,iorder,is_activated]
      edit:
        actions:
          _delete:       ~
          _list:
            credentials: [[PS_SYSTEM_DISTRICT_SHOW,PS_SYSTEM_DISTRICT_DETAIL,PS_SYSTEM_DISTRICT_EDIT]]
          _save:
            credentials: [PS_SYSTEM_DISTRICT_EDIT]
          _save_and_add:
            credentials: [PS_SYSTEM_DISTRICT_EDIT,PS_SYSTEM_DISTRICT_ADD]
      new:
        actions:          
          _list:
            credentials: [[PS_SYSTEM_DISTRICT_SHOW,PS_SYSTEM_DISTRICT_EDIT,PS_SYSTEM_DISTRICT_ADD,PS_SYSTEM_DISTRICT_DELETE]]
          _save:
            credentials: [PS_SYSTEM_DISTRICT_ADD]
          _save_and_add:
            credentials: [PS_SYSTEM_DISTRICT_ADD]