generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ServiceSplit
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_subject_splits
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: false
        object_actions: {}
        batch_actions: {}
      filter:
        display: []
        class: false
      form:    ~
      edit:    ~
      new:     ~
