indexSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js    
    - /psAdminThemePlugin/js/modules/ps_feature_branch_times.js: {position: last}
  stylesheets:    []
showSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js
  stylesheets:
    - /psAdminThemePlugin/css/fix_title_table.css
  
warningSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js    
    - /psAdminThemePlugin/js/modules/ps_feature_branch_times.js: {position: last}
  stylesheets:    []
  
detailByWeekSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js    
    - /psAdminThemePlugin/js/modules/ps_feature_branch_times.js: {position: last}
  stylesheets:    []
  
  
detailByWeek2Success:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js 
    - /psAdminThemePlugin/js/js_action_batch.js
 
exportSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js 
    - /psAdminThemePlugin/js/js_action_batch.js

importSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js 
    - /psAdminThemePlugin/js/js_action_batch.js
exportTem3Success:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js 
    - /psAdminThemePlugin/js/js_action_batch.js

importTem3Success:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js 
    - /psAdminThemePlugin/js/js_action_batch.js