<?php

/**
 * CollectedReceipt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    backend
 * @subpackage model
 * @author     Quanlymamnon.vn <contact@quanlymamnon.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CollectedReceipt extends BaseCollectedReceipt {

	public function getSumAmountByCollectedStudent($collected_student_id, $date = null) {

		return Doctrine::getTable ( 'CollectedReceipt' )->getSumAmountByCollectedStudent ( $collected_student_id, $date );
	}

	public function getAllReceiptOfCollectedStudent($collected_student_id) {

		return Doctrine::getTable ( 'CollectedStudent' )->getAllReceiptOfCollectedStudent ( $collected_student_id );
	}
}