<?php

/**
 * MyClass
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package backend
 * @subpackage model
 * @author Quanlymamnon.vn <contact@quanlymamnon.vn>
 * @version SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MyClass extends BaseMyClass {

	/**
	 * Lay giao vien cua lop
	 */
	public function getTeachers() {

		return Doctrine::getTable('PsTeacherClass')->getTeachersByClassId($this->getId());
	
	}

	/**
	 * Lay giao vien khong phai cua lop *
	 */
	public function getTeacherNotInClass() {

		return Doctrine::getTable('PsMember')->getTeachersNotInClass($this->getId(), $this->getPsCustomerId());
	
	}

	/**
	 * Lay so luong giao vien da duoc phan giao vien *
	 */
	public function getNumberTeacher() {

		return Doctrine::getTable('PsTeacherClass')->getNumberTeacherByClassId($this->getId());
	
	}

	/**
	 * Lay so luong dich vu cua lop *
	 */
	public function getNumberService() {

		return Doctrine::getTable('ClassService')->getNumberServiceByClassId($this->getId());
	
	}

	/**
	 * Tinh so luong hoc sinh dang theo hoc o lop: trang thai= Hoc thu ; Chinh thuc *
	 */
	public function getNumberStudentActivitie() {

		return Doctrine::getTable('StudentClass')->getNumberStudentActivitie($this->getId());
	
	}
	
	public function getNumberStudentClassActivitie() {
	
		return Doctrine::getTable('StudentClass')->getNumberStudentClassActivitie($this->getId());
	
	}

	/**
	 * Lay so luong hoc sinh cua lop: Tat ca trang thai *
	 */
	public function getNumberStudent() {

		return Doctrine::getTable('StudentClass')->getNumberStudentByClassId($this->getId());
	
	}

	/**
	 * Lay danh sach hoc sinh cua lop lien quan toi thong tin y te (Ko lay hoc sinh da bi danh dau xoa khoi he thong - deleted_at <> NULL)*
	 */
	public function getPsStudents() {

		return Doctrine::getTable('StudentClass')->getStudentsByClassId($this->getId());
	
	}

	/**
	 * Lay danh sach hoc sinh da tung trong lop(Ko lay hoc sinh da bi danh dau xoa khoi he thong - deleted_at <> NULL)*
	 */
	public function getStudentsOfClass() {

		return Doctrine::getTable('StudentClass')->getStudentsOfClass($this->getId (), $this->getPsCustomerId () );
	}
	
	/**
	 * Lay danh sach hoc sinh cua lop(Ko lay hoc sinh da bi danh dau xoa khoi he thong - deleted_at <> NULL)*
	 */
	public function getPsStudentsInClass() {

		return Doctrine::getTable ( 'StudentClass' )->getPsStudentsInClass ( $this->getId (), $this->getPsCustomerId () );
	}

	/**
	 * Lay danh sach hoc sinh cua lop tat ca trang thai(Ko lay hoc sinh da bi danh dau xoa khoi he thong - deleted_at <> NULL)*
	 */
	public function getPsStudentsInClassAllStatus() {

		return Doctrine::getTable ( 'StudentClass' )->getPsStudentsInClassAllStatus ( $this->getId (), $this->getPsCustomerId () );
	}

	/**
	 * Lay hoc sinh: Dang hoc - Hoc thu khong co trong 1 lop hoc *
	 */
	public function getPsStudentsNotInClass() {

		return Doctrine::getTable ( 'Student' )->getPsStudentsNotInClass ( $this->getId (), $this->getPsCustomerId () );
	}

	public function getActiveStudentInClass() {

		return Doctrine::getTable ( 'StudentClass' )->getStudentsActiveInClass ( $this->getId () );
	}

	// ***************END: Vesion 1.5 ***************************************
	public function getStudents($orderby = '') {

		return Doctrine::getTable ( 'Student' )->getStudentByClass ( $this->getId (), $orderby );
	}

	public function getStudentsByFilter($form_filter) {

		return Doctrine::getTable ( 'Student' )->getStudentsByFilter ( $this->getId (), $form_filter );
	}

	public function getService() {

		return Doctrine::getTable ( 'Service' )->getServicesByClass ( $this->getId () );
	}

	public function getServiceId() {

		$c [] = null;

		foreach ( $this->getService () as $value ) {
			$c [$value->getId ()] = $value->getId ();
		}

		return $c;
	}

	/**
	 * Lay danh sach sinh vien de diem danh di hoc theo thoi gian
	 *
	 * @param timestam $date
	 *
	 */
	public function getStudentServiceDiary($date) {

		return Doctrine::getTable ( 'Student' )->getStudentServiceDiaryByClass ( $this->getId (), $date );
	}
}