<?php

/**
 * PsAlbumCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsAlbumCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PsAlbumCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PsAlbumComment');
    }
    public function doSelectQuery(Doctrine_Query $query)
    {

        $a = $query->getRootAlias();

        $query->select (
            $a . '.*, ' .
            'c.school_name AS school_name, ' .
            'w.title as title_workplace,' .
            'p.title as album_title,' .
            'CONCAT(a.first_name, " ", a.last_name) AS relative_title,' .
            'CONCAT(u.first_name, " ", u.last_name) AS updated_by' );

            $query->leftJoin ( $a . '.UserUpdated u' );
            $query->leftJoin ( $a . '.PsCustomer c');
            $query->leftJoin ( $a . '.PsWorkPlaces w');
            $query->leftJoin ( $a . '.PsAlbum p');
            $query->leftJoin ( $a . '.Relative a');

         return $query;
    }
}