<?php

/**
 * PsCmsNotificationsClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsCmsNotificationsClassTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsCmsNotificationsClassTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsCmsNotificationsClass' );
	}
	public function getCheckNotificationClassByNotificationId($notification_id) {
		
		$query = $this->createQuery ( 'm' );
		
		$query->select ( '*' );
		$query->addWhere ( 'm.ps_notification_id = ?', $notification_id );
		
		return $query->execute ();
	}
}