<?php

/**
 * PsCmsReceivedNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsCmsReceivedNotificationTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsCmsReceivedNotificationTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsCmsReceivedNotification' );
	}

	public function getReceivedNotificationByNotificationId($notification_id, $user_id) {

		$query = $this->createQuery ( 'm' );

		$query->select ( 'm.id AS id, ' . 'm.user_id AS user_id, ' . 'm.private_key AS private_key, ' . 'm.is_read, m.is_delete as is_delete,' . 'm.date_at AS date_at, ' );

		$query->addWhere ( 'm.ps_cms_notification_id = ?', $notification_id );

		$query->addWhere ( 'm.user_id = ?', $user_id );

		return $query->fetchOne ();
	}

	public function getListReceivedNotificationByNotificationId($notification_id, $user_id) {
		
		$query = $this->createQuery ( 'm' );
		
		$query->select ( 'm.id AS id, ' . 'm.user_id AS user_id, ' . 'm.private_key AS private_key, ' . 'm.is_read, m.is_delete as is_delete,' . 'm.date_at AS date_at, ' );
		
		$query->addWhere ( 'm.ps_cms_notification_id = ?', $notification_id );
		
		$query->addWhere ( 'm.user_id = ?', $user_id );
		
		return $query->execute();
	}
	
	public function getCheckNotificationByNotificationId($notification_id) {

		$query = $this->createQuery ( 'm' );

		$query->select ( 'm.id AS id, ' . 'm.user_id AS user_id, ' . 'm.private_key AS private_key, ' . 'm.is_read, m.is_delete as is_delete,' . 'm.date_at AS date_at, ' );
		$query->addWhere ( 'm.ps_cms_notification_id = ?', $notification_id );

		return $query->execute ();
	}
}
    
