<?php

/**
 * PsEmailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsEmailsTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsEmailsTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsEmails' );
	}

	/**
	 * Kiem tra ton tai email
	 *
	 * @return boolean - true: Co the su dung
	 */
	public function checkEmailExits($email, $obj_id = null, $obj_type) {

		$q = $this->createQuery ()
			->select ( 'ps_email, obj_id, obj_type' );

		$q->where ( 'ps_email = ?', $email );

		$ps_emails = $q->fetchOne ();

		if (! $ps_emails)
			return false;
		else {

			// return (($obj_id > 0) && ($ps_emails->getObjId() == $obj_id) && ($ps_emails->getObjType() == $obj_type));

			if ($obj_id > 0 && ($ps_emails->getObjId () == $obj_id) && ($ps_emails->getObjType () == $obj_type)) { // edit
				return false;
			} else {
				return true;
			}
		}
	}

	/**
	 * Kiem tra ton tai email
	 */
	public function findOneByObj($obj_id, $obj_type) {

		$q = $this->createQuery ()
			->select ( '*' );

		$q->where ( 'obj_id = ?', $obj_id );

		$q->andWhere ( 'obj_type = ?', $obj_type );

		return $q->fetchOne ();
	}
}