<?php

/**
 * PsFeeReceivableStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsFeeReceivableStudentTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsFeeReceivableStudentTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsFeeReceivableStudent' );
	}

	/**
	 * Lay ra cac khoan thu cua hoc sinh
	 *
	 * @author Phung Van Thanh
	 */
	public function getAllReceiptStudent($receipt_id) {

		$q = $this->createQuery ( 'fr' )
			->select ( 'fr.title as title, fr.amount as amount, fr.spent_number as spent_number, fr.note as note, fr.updated_at as updated_at' );
		$q->addSelect ( 'CONCAT(u.first_name," ",u.last_name) AS updated_by' );
		$q->leftJoin ( 'fr.UserUpdated u' );
		$q->addWhere ( 'fr.ps_fee_receipt_id =?', $receipt_id );
		$q->orderBy ( 'fr.id' );
		return $q->execute ();
	}
}