<?php

/**
 * PsHistoryMobileAppPayAmounts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    truongnet.com
 * @subpackage model
 * @author     truongnet.com <contact@truongnet.com - ntsc279@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PsHistoryMobileAppPayAmounts extends BasePsHistoryMobileAppPayAmounts {
}