<?php

/**
 * PsMemberWorkingTimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsMemberWorkingTimeTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsMemberWorkingTimeTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsMemberWorkingTime' );
	}

	// Ham ton tai rang buoc giua MemberDepartment va Department
	public function checkMemberWorkingTimeExits($ps_workingtime_id, $objid = null) {

		$query = $this->createQuery ()
			->select ( 'id' );

		if (isset ( $ps_workingtime_id )) {

			if (is_array ( $ps_workingtime_id ) > 0)

				$query->whereIn ( 'ps_workingtime_id', $ps_workingtime_id );

			else

				$query->andWhere ( 'ps_workingtime_id=?', $ps_workingtime_id );
		}

		if ($objid > 0)
			$query->andwhere ( 'id <> ?', $objid );

		$records = $query->execute ();

		return count ( $records ) ? true : false;
	}

	// Lay ra khung gio lam viec cua giao vien
	public function getMemberWorkingTimeByMemberId($member_id, $track_at) {

		$track_at = $track_at ? $track_at : '';

		$query = $this->createQuery ( 'a' );
		$query->select ( 'a.id AS id,' . 'a.start_at AS start_at,' . 'a.stop_at AS stop_at,' . 'wt.title AS title,' . 'TIME_FORMAT(wt.start_time, "%H:%i") AS start_time,' . 'TIME_FORMAT(wt.end_time, "%H:%i") AS end_time,' . 'a.note AS note,' . 'CONCAT(uc.first_name, " ", uc.last_name) AS creator_by, ' . 'CONCAT(ud.first_name, " ", ud.last_name) AS updated_by, ' . 'CONCAT(mb.first_name, " ", mb.last_name) AS member_name, ' . 'cus.school_name AS school_name,' . 'a.updated_at AS updated_at,' );
		$query->leftJoin ( 'a.PsMember mb' );

		$query->leftJoin ( 'a.PsWorkingTime wt' );

		$query->leftJoin ( 'wt.PsCustomer cus' );

		$query->leftJoin ( 'a.UserCreated uc' );

		$query->leftJoin ( 'a.UserUpdated ud' );

		if ($track_at != '') {

			$query->addWhere ( 'DATE_FORMAT(a.start_at,"%Y%m%d") <= ?', date ( 'Ymd', strtotime ( $track_at ) ) );
			$query->addWhere ( 'a.stop_at IS NULL OR DATE_FORMAT(a.stop_at,"%Y%m%d") >=?', date ( 'Ymd', strtotime ( $track_at ) ) );
		}

		$query->addWhere ( 'a.ps_member_id=?', $member_id );

		$query->addWhere ( 'wt.is_activated=?', PreSchool::ACTIVE );

		$query->orderBy ( 'a.created_at DESC' );

		return $query->execute ();
	}
}