<?php

/**
 * PsNhatKyCongNoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsNhatKyCongNoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PsNhatKyCongNoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PsNhatKyCongNo');
    }
}