<?php

/**
 * PsProfessionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsProfessionalTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsProfessionalTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsProfessional' );
	}

	/**
	 * FUNCTION: doSelectQuery(Doctrine_Query $query)
	 *
	 * @param
	 *        	Doctrine SQL
	 * @return string SQL
	 */
	public function doSelectQuery(Doctrine_Query $query) {

		$a = $query->getRootAlias ();

		$query->select ( $a . '.id AS id, ' . $a . '.title AS title, ' . $a . '.description AS description, ' . $a . '.iorder AS iorder, ' . $a . '.is_activated AS is_activated, ' . $a . '.updated_at AS updated_at,' . 'cus.title AS customer_title, ' . 'CONCAT(u.first_name, " ", u.last_name) AS updated_by' );

		$query->leftJoin ( $a . '.PsCustomer cus' );
		$query->leftJoin ( $a . '.UserUpdated u' );

		$query->where ( $a . '.ps_customer_id IS NULL' ); // Lay danh sach chung

		if (! myUser::credentialPsCustomers ( 'PS_HR_PROFESSIONAL_FILTER_SCHOOL' ) && myUser::getPscustomerID () > 0)
			$query->orWhere ( $a . '.ps_customer_id = ?', ( int ) myUser::getPscustomerID () );
		else
			$query->orWhere ( '1=1' );

		return $query;
	}
}