<?php

/**
 * PsTemplateExportsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsTemplateExportsTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsTemplateExportsTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsTemplateExports' );
	}
}