<?php

/**
 * PsTimesheetSummarysTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsTimesheetSummarysTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsTimesheetSummarysTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsTimesheetSummarys' );
	}

	public function getMemberTimesheet($member_id, $year_month) {

		$date_at = '01-' . $year_month;
		$date_next = '31-' . $year_month;
		$query = $this->createQuery ( 'tsm' )
			->select ( 'tsm.member_id as member_id, tsm.timesheet_at as timesheet_at, tsm.number_time as number_time' )
			->where ( 'tsm.member_id = ?', ( int ) $member_id )
			->addWhere ( 'DATE_FORMAT(tsm.timesheet_at,"%Y%m%d") >= ?', date ( "Ymd", strtotime ( $date_at ) ) )
			->addWhere ( 'DATE_FORMAT(tsm.timesheet_at,"%Y%m%d") <= ?', date ( "Ymd", strtotime ( $date_next ) ) );
		return $query->execute ();
	}

	public function getCountTimesheetMember($member_id, $year_month) {

		$date_at = '01-' . $year_month;
		$date_next = '31-' . $year_month;
		$query = $this->createQuery ( 'tsm' )
			->select ( 'tsm.member_id as member_id, tsm.timesheet_at as timesheet_at, tsm.number_time as number_time' )
			->where ( 'tsm.member_id = ?', ( int ) $member_id )
			->addWhere ( 'DATE_FORMAT(tsm.timesheet_at,"%Y%m%d") >= ?', date ( "Ymd", strtotime ( $date_at ) ) )
			->addWhere ( 'DATE_FORMAT(tsm.timesheet_at,"%Y%m%d") <= ?', date ( "Ymd", strtotime ( $date_next ) ) );
		return $query->count ();
	}

	// Lay ra tat ca nhan vien trong thang
	public function getTimesheetSummaryOfMember($ps_customer_id, $ps_workplace_id, $ps_department_id, $year_month) {

		$date_at = '01-' . $year_month;
		$date_next = '31-' . $year_month;

		$query = $this->createQuery ( 'tsm' );

		$query->select ( 'tsm.id AS tsm_id, ' . 'tsm.member_id AS member_id, ' . 'tsm.number_time AS number_time, ' . 'tsm.timesheet_at AS timesheet_at, ' . 'tsm.description AS description, ' . 'mb.id AS mb_id, ' . 'cus.school_code AS school_code,' . 'CONCAT(mb.first_name, " ", mb.last_name) AS member_name,' );

		$query->addSelect ( 'CONCAT(u.first_name, " ", u.last_name) AS updated_by' );

		$query->leftJoin ( 'tsm.PsMember mb' );

		$query->innerJoin ( 'mb.PsCustomer cus' );

		$query->leftJoin ( 'mb.PsMemberDepartments dpm' );

		$query->leftJoin ( 'dpm.PsDepartment dp' );

		$query->innerJoin ( 'tsm.UserUpdated u' );

		if ($department_id > 0)
			$query->addWhere ( 'dpm.ps_department_id = ?', $ps_department_id );
		elseif ($ps_workplace_id > 0)
			$query->addWhere ( 'dp.ps_workplace_id = ?', $ps_workplace_id );
		else
			$query->addWhere ( 'mb.ps_customer_id = ?', $ps_customer_id );

		$query->andWhere ( ' DATE_FORMAT(tsm.timesheet_at,"%Y%m%d") >= ?', date ( 'Ymd', strtotime ( $date_at ) ) );

		$query->andWhere ( ' DATE_FORMAT(tsm.timesheet_at,"%Y%m%d") <= ?', date ( 'Ymd', strtotime ( $date_next ) ) );

		$query->orderBy ( 'mb.last_name desc, tsm.timesheet_at desc' );

		return $query->execute ();
	}
}