<?php

/**
 * PsWardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PsWardTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PsWardTable
	 */
	public static function getInstance() {

		return Doctrine_Core::getTable ( 'PsWard' );
	}

	/**
	 * Lay gia tri Max cua iorder, return: int - max order
	 *
	 * @return int
	 */
	public function getMaxIorder() {

		return $this->createQuery ()
			->select ( 'MAX(iorder) AS max_order' )
			->fetchOne ()
			->getMaxOrder ();
	}

	/**
	 * FUNCTION: doSelectQuery(Doctrine_Query $query)
	 *
	 * @param
	 *        	Doctrine SQL
	 * @return string SQL
	 */
	public function doSelectQuery(Doctrine_Query $query) {

		$a = $query->getRootAlias ();

		$query->select ( $a . '.id AS id, ' . $a . '.s_code AS s_code, ' . $a . '.name AS name, ' . $a . '.iorder AS iorder, ' . $a . '.is_activated AS is_activated, ' . $a . '.updated_at AS updated_at,' . 'd.name AS district_name,' . 'CONCAT(u.first_name, " ", u.last_name) AS updated_by' );

		$query->innerJoin ( $a . '.PsDistrict d' );

		$query->leftJoin ( $a . '.UserUpdated u' );

		return $query;
	}

	/**
	 * FUNCTION: getPsWardsByPsDistrictId($ps_district_id)
	 *
	 * @param $ps_district_id -
	 *        	int
	 *        	
	 * @return list obj
	 */
	public function getPsWardsByPsDistrictId($ps_district_id = null) {

		$q = $this->createQuery ()
			->select ( 'id, name' );

		if ($ps_district_id != '')
			$q->where ( 'ps_district_id = ?', $ps_district_id );

		$q->orderBy ( 'iorder' );

		return $q->execute ();
	}

	/**
	 * FUNCTION: getPsWardsByPsDistrictId($ps_district_id)
	 *
	 * @param $ps_district_id -
	 *        	int
	 *        	
	 * @return list obj
	 */
	public function getChoicePsWard($ps_district_id = null) {

		// Lay Quan/Huyen
		$districts = $this->getPsWardsByPsDistrictId ( $ps_district_id );

		$chois = array ();

		foreach ( $districts as $district ) {

			$chois [$district->getId ()] = $district->getName ();
		}

		return $chois;
	}

	/**
	 * FUNCTION: getGroupPsWards($country_code)
	 *
	 * @param $country_code -
	 *        	string, ma quoc gia
	 *        	
	 * @return $list
	 */
	public function getGroupPsWards($country_code = '') {

		// Lay tinh thanh
		$provinces = Doctrine::getTable ( 'PsProvince' )->loadPsProvinceByCountry ( $country_code );

		$chois = array ();

		foreach ( $provinces as $province ) {
			foreach ( $province->getPsDistricts () as $district ) {
				// $chois [$province->getName ()] [$district->getId ()] = $district->getName();
				foreach ( $district->getPsWards () as $ps_ward ) {
					$chois [$province->getName ()] [$district->getName ()] [$ps_ward->getId ()] = $ps_ward->getName ();
				}
			}
		}
		return $chois;
	}
}