<?php
/**
 * Receipt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    backend
 * @subpackage model
 * @author     Quanlymamnon.vn <contact@quanlymamnon.vn>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Receipt extends BaseReceipt {

	
	/**
	 * Ham lay So thu tu thanh toan lon nhat cua 1 co so
	 *
	 * @return int
	 */
	public function getMaxPaymentOrder() {
		
		$infoClass 		 = Doctrine::getTable ( "StudentClass" )->getClassActivateByStudent ($this->getStudentId(),$this->getReceiptDate());		
		
		$ps_workplace_id = $infoClass ? $infoClass->getPsWorkplaceId () : 0;
		
		return Doctrine::getTable ( 'Receipt' )->getMaxPaymentOrder($this->getPsCustomerId(), $ps_workplace_id, $this->getPaymentDate())->getMaxPaymentOrder();		
	}
	
	public function findAllOfReceipt() {

		return Doctrine::getTable ( 'CollectedReceipt' )->findAllOfReceipt ( $this->getId () );
	}

	public function removeReceipt() {

		$receipt_id = $this->getId ();

		try {

			$this->delete ();

			$collected_receipt = Doctrine::getTable ( 'CollectedReceipt' )->findByReceiptId ( $receipt_id );

			// Cap nhat lai Tong so tien da nop trong collected_student

			foreach ( $collected_receipt as $obj ) {

				$collected_student_id = $obj->get ( 'collected_student_id' );

				// Xoa
				$obj->delete ();

				// Kiem tra xem collected_student_id nay con o Phieu thu nao khong
				$collReceipt = Doctrine::getTable ( 'CollectedReceipt' )->findByCollectedStudentId ( $collected_student_id );

				$collectedStudent = Doctrine::getTable ( 'CollectedStudent' )->find ( $collected_student_id );

				if (! count ( $collReceipt )) { // Neu khong con xoa bo collected_student nay

					$collectedStudent->delete ();
				} else { // Trai lai update gia tri Tong da nop

					// Lay tong so tien da nop vao
					$collReceiptAmount = Doctrine::getTable ( 'CollectedReceipt' )->getSumAmountByCollectedStudent ( $collected_student_id );

					$collectedStudent->setAmount ( $collReceiptAmount ? $collReceiptAmount->get ( 'amount' ) : 0 );

					$collectedStudent->save ();
				}
			}
		} catch ( Exception $e ) {
		}
	}
}