<?php

/**
 * Receivable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Preschool
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Receivable extends BaseReceivable {

	/**
	 * Lay danh sach cac khoan phai thu tru ra nhung khoan da duoc add truoc do
	 *
	 * @param int $student_id
	 * @param timestamp $date:
	 *        	Ngay nhap du lieu
	 */
	public function getReceivablesSkipIfExists($student_id, $date) {

		return Doctrine::getTable ( "Receivable" )->getReceivablesSkipIfExists ( $student_id, $date );
	}

	// Lay so luong da gan cho hoc sinh
	public function getCountReceivableStudent() {

		return Doctrine::getTable ( 'ReceivableStudent' )->getCountReceivableStudentOfReceivableId ( $this->getId () );
	}

	// Lay so luong da gan cho hoc sinh
	public function getCountReceivableTemp() {

		return Doctrine::getTable ( 'ReceivableTemp' )->getCountReceivableTempOfReceivableId ( $this->getId () );
	}
}