<?php

/**
 * StudentServiceDiary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Preschool
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StudentServiceDiary extends BaseStudentServiceDiary {

	/**
	 * Lay gia gia cua dich vu tuong ung voi thoi diem nhap du
	 *
	 * @param unknown_type $date
	 */
	public function getServiceDetailByDate($date) {

		return Doctrine::getTable ( 'ServiceDetail' )->getServiceDetailByDate ( $this->getServiceId (), $date );
	}
}