generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsConfigLatePayment
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_config_late_payments
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        table_method: doSelectQuery
        max_per_page: 35
      filter:
        display: [school_year_id,ps_customer_id,ps_workplace_id,is_activated]
      form:
        display: [ps_customer_id,ps_workplace_id,school_year_id,from_date,to_date,price,note,is_activated]
      edit:
        actions:
          _list: ~         
          _save: ~
          _save_and_add: ~
          _delete: ~
      new:
        actions:
          _list: ~         
          _save: ~
          _save_and_add: ~
