generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsMemberAbsents
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_member_absents
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy, label: Updated by}
      list:
        title: Member absents index
        display: [member_id,absent_at,absent_type,description,updated_at]
        table_method: doSelectQuery
        actions:
          _new: {credentials: PS_HR_ABSENTS_ADD}
        object_actions:
          _edit: {credentials: PS_HR_ABSENTS_EDIT}
          _delete: {credentials: PS_HR_ABSENTS_DELETE,confirm: "Are you sure?"}
        batch_actions:
         _delete: {credentials: PS_HR_ABSENTS_DELETE,confirm: "Are you sure?"}
      filter:
        display: [school_year_id,ps_customer_id,ps_workplace_id,ps_department_id,member_id,keywords]
      form:
        display: [ps_workplace_id,ps_department_id,member_id,absent_at,absent_type,description]
      edit:    ~
      new:     ~
