<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Preschool
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {
	
	public function getUserInfoCustomer() {
		return Doctrine::getTable ( 'sfGuardUser' )->getUserInfoCustomer ( $this->getId (), $this->getUserType () );
	}
	
	// Lay Profile co ban cua user
	public function getProfileShort() {
		if ($this->getUserType () == PreSchool::USER_TYPE_TEACHER || $this->getUserType () == PreSchool::USER_TYPE_MANAGER) {
			return Doctrine::getTable ( 'PsMember' )->getProfileShort ( $this->getMemberId () );
		} elseif ($this->getUserType () == PreSchool::USER_TYPE_RELATIVE) {
			return Doctrine::getTable ( 'Relative' )->getProfileShort ( $this->getMemberId () );
		}
	}
	
	public function getSchoolCode() {
	
	}
}