generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsCategoryReview
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_category_review
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
      list: 
        display: 	[title, note, status, updated_by, updated_at]
        table_method: doSelectQuery
      filter: 
        display: [ps_customer_id, ps_workplace_id, title, status]
      form: ~
        # display: [ps_customer_id,ps_workplace_id,title,is_global,note,iorder,is_activated]
      edit: ~
        # display:
          # Thông tin Album: [ps_customer_id, ps_workplace_id, total_like ,total_comment, member_id, class_id, title, status]
          # File đính kèm: [_list_file]
      new: ~
