
# newSuccess:
  # javascripts:    [jquery-1.6.2.js]
  # has_layout:     true
  # layout:   layout_nomenu


forChoiceSuccess:
  has_layout:     true
  layout:   layout_nomenu
  javascripts:    
    - jquery-1.3.2.min.js
    - jqModal.js
    - jqDnR.js
    - jquery.validate.js
    - kid_garden.js
  stylesheets:    
    - kid_garden.css

forChoiceNewSuccess:
  has_layout:     true
  layout:   layout_nomenu
  javascripts:    
    - jquery-1.3.2.min.js
    - jqModal.js
    - jqDnR.js
    - jquery.validate.js
    - kid_garden.js
  stylesheets:    
    - kid_garden.css

forBatchSuccess:
  has_layout:     true
  layout:   layout_nomenu
  javascripts:    
    - jquery-1.3.2.min.js
    - jqModal.js
    - jqDnR.js
    - jquery.validate.js
    - kid_garden.js
  stylesheets:    
    - kid_garden.css
   
addNewSuccess:
  has_layout:     true
  layout:   layout_nomenu
  javascripts:    
    - jquery-1.3.2.min.js
    - jqModal.js
    - jqDnR.js
    - jquery.validate.js
    - kid_garden.js
  stylesheets:    
    - kid_garden.css