# You can find more information about this file on the symfony website: dung cho thiet lap man hinh
# http://www.symfony-project.org/reference/1_4/en/08-Security
default:
  is_secure:   true # Yeu cau toan bo ung dung can phai dang nhap

all:
  is_secure: true

# quyen cua action
# Hien thi danh sach
index:
  is_secure: true
  credentials: [[PS_SYSTEM_CONTRACT_SHOW, PS_SYSTEM_CONTRACT_ADD,PS_SYSTEM_CONTRACT_EDIT,PS_SYSTEM_CONTRACT_DELETE]]   

new:
  is_secure: true
  credentials: [PS_SYSTEM_CONTRACT_ADD]  

create:
  is_secure: true
  credentials: [PS_SYSTEM_CONTRACT_ADD]

edit:
  is_secure: true
  credentials: [PS_SYSTEM_CONTRACT_EDIT]  

delete:
  is_secure: true
  credentials: [PS_SYSTEM_CONTRACT_DELETE]