<?php
// Dinh nghia ma screen
class PsScreenCode {
	
	// Chat
	const PS_CONST_SCREEN_HOME = '001';

	const PS_CONST_SCREEN_SERVICE = '002';

	const PS_CONST_SCREEN_CAMERA = '003';
	
	// App phụ huynh - Man hinh Hoat động
	const PS_CONST_SCREEN_FEATURE = '004';

	const PS_CONST_SCREEN_TEACHER_SCHEDULE = '004';
	
	// Lich len lop
	const PS_CONST_SCREEN_MORE = '005';
	
	// Chuc nang Thong bao
	const PS_CONST_SCREEN_CMSNOTIFICATION = '006';

	const PS_CONST_SCREEN_CMSNOTIFICATION_DETAIL = '006-01';

	const PS_CONST_SCREEN_SCHEDULE = '007';
	
	// Lich hoc
	const PS_CONST_SCREEN_TEACHER_CLASS_SCHEDULES = '007';
	
	// Lich day
	const PS_CONST_SCREEN_TODAY_STUDENT = '008';

	const PS_CONST_SCREEN_TEACHER_LOGTIME = '008';
	
	// Man hình ket qua danh gia hoc sinh
	const PS_CONST_SCREEN_COMMENT_STUDENT = '009';
	
	// Danh gia nhan xet hoc sinh
	const PS_CONST_SCREEN_TEACHER_COMMENT_STUDENT = '009';

	const PS_CONST_SCREEN_GROWTHSTUDENT = '010';

	const PS_CONST_SCREEN_RELATIVES = '011';

	const PS_CONST_SCREEN_RELATIVES_DETAIL = '011-01';

	const PS_CONST_SCREEN_REPORT_FEE = '012';

	const PS_CONST_SCREEN_SETTING = '013';

	const PS_CONST_SCREEN_USER_INFO = '014';

	const PS_CONST_SCREEN_SETTING_LANGUAGE = '015';

	const PS_CONST_SCREEN_SETTING_NOTIFICATION = '016';
	
	// Cai dat Thong bao và Tin nhan
	const PS_CONST_SCREEN_SETTING_DISPLAY = '017';

	const PS_CONST_SCREEN_CHANGE_PASSWORD = '018';

	const PS_CONST_SCREEN_ABOUT = '019';

	const PS_CONST_SCREEN_LOGOUT = '020';

	const PS_CONST_SCREEN_CHAT = '021';

	const PS_CONST_SCREEN_ATTENDANCE = '022';

	const PS_CONST_SCREEN_MENU = '023';

	const PS_CONST_SCREEN_ALBUMS = '024';

	const PS_CONST_SCREEN_ALBUM_DETAIL = '024-1';

	const PS_CONST_SCREEN_ARTICLES = '025';

	const PS_CONST_SCREEN_ARTICLES_DETAIL = '025-1';
	
	const PS_CONST_SCREEN_OFFSCHOOL = '026';
	
	const PS_CONST_SCREEN_OFFSCHOOL_DETAIL = '026-1';
	
	const PS_CONST_SCREEN_OFFSCHOOL_CONFIRMED = '027'; // Xin nghỉ đã xác nhận
	
	const PS_CONST_SCREEN_ADVICE_UNCONFIMRED = '028-1';// Dặn dò Chưa duyệt/ Dặn dò đã gửi
	
	const PS_CONST_SCREEN_ADVICE_CONFIMRED = '028-2';// Dặn dò đã xác nhận
	
	const PS_CONST_SCREEN_ADVICE_DETAIL = '028-3';
}

