generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsProvince
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_province
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit: {credentials: PS_SYSTEM_PROVINCE_EDIT}
        _new: {credentials: PS_SYSTEM_PROVINCE_ADD}
        _delete: {credentials: PS_SYSTEM_PROVINCE_DELETE}
      fields:  
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
      list:    
        display: [=s_code,=name,iorder,is_activated, updated_by,updated_at]
        sort: [iorder, asc]
        table_method: doSelectQuery
      filter:  ~
      form: ~
      edit:
        actions:
          _delete:       ~
          _list:
            credentials: [[PS_SYSTEM_PROVINCE_SHOW,PS_SYSTEM_PROVINCE_DETAIL,PS_SYSTEM_PROVINCE_EDIT]]
          _save:
            credentials: [PS_SYSTEM_PROVINCE_EDIT]
          _save_and_add:
            credentials: [PS_SYSTEM_PROVINCE_EDIT,PS_SYSTEM_PROVINCE_ADD]
      new:
        actions:          
          _list:
            credentials: [[PS_SYSTEM_PROVINCE_SHOW,PS_SYSTEM_PROVINCE_EDIT,PS_SYSTEM_PROVINCE_ADD,PS_SYSTEM_PROVINCE_DELETE]]
          _save:
            credentials: [PS_SYSTEM_PROVINCE_ADD]
          _save_and_add:
            credentials: [PS_SYSTEM_PROVINCE_ADD]    
