indexSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
  stylesheets:
#    - /psAdminThemePlugin/css/fix_title_table.css
  
  
importSuccess:
  javascripts:
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js

statisticSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/js_action_batch.js

showSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/n2vi.min.js

importreceiptSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js
    
importLastMonthSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js


importAmountLastMonthSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js


amountLastMonthExportSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js


importRegisterServiceSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js

exportRegisterServiceSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js
importTemplateSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js

exportTemplateSuccess:
  javascripts:
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
    - /psAdminThemePlugin/js/libs/i18n/ui.datepicker-vi.js
