generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsOffSchool
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_off_school
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        is_activated : {label: Status}
        updated_at : {date_format: HH:mm dd-MM-yyyy}
        date_at : {date_format: HH:mm dd-MM-yyyy}
        user_create_id : {label: User Create?}
        relative_id: {label: Relative}
        description: {label: Reason}
      list:
        title: Student Off School List
        display: [ps_class_id,relative_id,student_id,description,is_activated,date_at,date,created_at]
        max_per_page: 10
        table_method: doSelectQuery
        actions:
          _new: {credentials: PS_STUDENT_OFF_SCHOOL_ADD}
        object_actions:
#          _detail: {credentials: PS_STUDENT_OFF_SCHOOL_DETAIL}
          _edit: {credentials: PS_STUDENT_OFF_SCHOOL_EDIT}
          _delete: {credentials: PS_STUDENT_OFF_SCHOOL_DELETE,confirm: "Are you sure?"}
        batch_actions:
         _delete: {credentials: PS_STUDENT_OFF_SCHOOL_DELETE,confirm: "Are you sure?"}
      filter:
        display:  [school_year_id,ps_customer_id,ps_workplace_id,ps_class_id,is_activated,start_at,stop_at]
      form:
        display: [ps_workplace_id,config_time,ps_class_id,student_id,relative_id,user_id,date_at,date,description,is_activated,reason_illegal,created_at]
      edit: ~
      new: ~
