# You can find more information about this file on the symfony website: dung cho thiet lap man hinh
# http://www.symfony-project.org/reference/1_4/en/08-Security
default:
  is_secure:   true # Yeu cau toan bo ung dung can phai dang nhap

all:
  is_secure: true

# quyen cua action
# Hien thi danh sach
index:
  is_secure: true
  credentials: [[PS_FEE_CONFIG_LATE_FEES_FILTER_SCHOOL,PS_FEE_CONFIG_LATE_FEES_SHOW,PS_FEE_CONFIG_LATE_FEES_EDIT,PS_FEE_CONFIG_LATE_FEES_DETAIL,PS_FEE_CONFIG_LATE_FEES_ADD,PS_FEE_CONFIG_LATE_FEES_DELETE]]   

new:
  is_secure: true
  credentials: [PS_FEE_CONFIG_LATE_FEES_ADD]  

create:
  is_secure: true
  credentials: [PS_FEE_CONFIG_LATE_FEES_ADD]

edit:
  is_secure: true
  credentials: [PS_FEE_CONFIG_LATE_FEES_EDIT]  

delete:
  is_secure: true
  credentials: [PS_FEE_CONFIG_LATE_FEES_DELETE]
  
detail:
  is_secure: true
  credentials: [PS_FEE_CONFIG_LATE_FEES_DETAIL]
  

  
