generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Service
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_subjects
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _detail: {credentials: [PS_STUDENT_SUBJECT_EDIT,PS_STUDENT_SUBJECT_DETAIL,PS_STUDENT_SUBJECT_DELETE,PS_STUDENT_SUBJECT_FILTER_SCHOOL]}
        _edit: {credentials: PS_STUDENT_SUBJECT_EDIT}
        _new: {credentials: PS_STUDENT_SUBJECT_ADD}
        _delete: {credentials: PS_STUDENT_SUBJECT_DELETE,confirm: "Are you sure wish delete this subject?"}
      fields:  
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
        detail_at: {date_format: dd/MM/yyyy}
        ps_image_id: {label: Icon}
      list:
        title: Subjects list        
        display: [_file_name,=title,group_name,iorder,number_course,_list_field_number_option_subject,_service_detail, is_activated,updated_at]         
        sort: [iorder, asc]
        table_method: doSelectQuerySubjects
        max_per_page: {}
        object_actions:
          _detail: ~
          _edit: ~
          _delete: ~        
        batch_actions:
         #_delete: ~
         _updateOrder: {credentials: PS_STUDENT_SUBJECT_EDIT,label: Update Order}
      filter:
        display: [ps_school_year_id,ps_customer_id,ps_workplace_id,service_group_id,enable_roll,is_default,is_activated,title] 
      form:    ~
      edit:
       title: Editing subjects: %%title%%
       actions:
         _list: ~
         _save:
           label: Save
           action: submit
         _delete:
           confirm: "Are you sure wish delete this subject?"
       display:
         Subjects infomation: [ps_customer_id,service_group_id,ps_workplace_id,ps_school_year_id,title,enable_roll,is_default,ps_image_id,mode,note,iorder,description,is_activated]
         Price information and the time apply: [_form_edit_servicedetail]
      new:
       title: New subjects
       actions:
         _list: ~
#         new_detail:
#           lable: New detail
#           action: addDetail
#           credentials: [[PS_STUDENT_SUBJECT_DETAIL_ADD, PS_STUDENT_SUBJECT_DETAIL_EDIT]]
         _save:
           label: Save
           action: submit
       display:
         Subjects infomation: [ps_customer_id,service_group_id,ps_workplace_id,ps_school_year_id,title,enable_roll,is_default,ps_image_id,mode,note,iorder,description,is_activated]
         Price information and the time apply: [_form_new_servicedetail]
