generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsPolicyGroup
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_policy_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
      list: 
        display: 	[policy_code, title, level, is_type, updated_by, updated_at]
        table_method: doSelectQuery
      filter: 
         display: [ps_customer_id, ps_workplace_id,title]
      form: ~
        # display: [ps_customer_id,ps_workplace_id,title,is_global,note,iorder,is_activated]
      edit: 
        display:
          Policy Information: [ps_customer_id,ps_workplace_id,policy_code,title,level,is_type]
          Service Information: [_list_service]
      new:
        display:
          Policy Information: [ps_customer_id,ps_workplace_id,policy_code,title,level,is_type]
          Service Information: [_list_service]
