generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsDepartment
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_department
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit: {credentials: PS_HR_DEPARTMENT_EDIT}
        _new: {credentials: PS_HR_DEPARTMENT_ADD}
        _delete: {credentials: PS_HR_DEPARTMENT_DELETE}
      fields:  
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}        
        customer_title : {label: Ps customer}
      list:    
        display: [title,customer_title,description,iorder,is_activated, updated_by,updated_at]
        sort: [iorder, asc]
        table_method: doSelectQuery
        batch_actions: {}
      filter:
        display: 	[ps_customer_id,ps_workplace_id,is_activated,title]
      form:    ~
      edit:
        actions:
          _delete:       ~
          _list:
            credentials: [[PS_HR_DEPARTMENT_SHOW,PS_HR_DEPARTMENT_DETAIL,PS_HR_DEPARTMENT_EDIT]]
          _save:
            credentials: [PS_HR_DEPARTMENT_EDIT]
          _save_and_add:
            credentials: [PS_HR_DEPARTMENT_EDIT,PS_HR_DEPARTMENT_ADD]
      new:
        actions:          
          _list:
            credentials: [[PS_HR_DEPARTMENT_SHOW,PS_HR_DEPARTMENT_EDIT,PS_HR_DEPARTMENT_ADD,PS_HR_DEPARTMENT_DELETE]]
          _save:
            credentials: [PS_HR_DEPARTMENT_ADD]
          _save_and_add:
            credentials: [PS_HR_DEPARTMENT_ADD]
