generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Relationship
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          relationship_psRelationship
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit: {credentials: PS_SYSTEM_RELATIONSHIP_EDIT}
        _new: {credentials: PS_SYSTEM_RELATIONSHIP_ADD}
        _delete: {credentials: PS_SYSTEM_RELATIONSHIP_DELETE}                            
      fields:  
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
      list:
        display: [=title,description,iorder, is_activated, updated_by,updated_at]
        sort: [iorder, asc]
        table_method: doSelectQuery        
      filter:
        display: [title,description,is_activated]
      form:
        display: [title,iorder,description,is_activated]
      edit:
        actions:
          _delete:       ~
          _list:
            credentials: [[PS_SYSTEM_RELATIONSHIP_SHOW,PS_SYSTEM_RELATIONSHIP_DETAIL,PS_SYSTEM_RELATIONSHIP_EDIT]]
          _save:
            credentials: [PS_SYSTEM_RELATIONSHIP_EDIT]
          _save_and_add:
            credentials: [PS_SYSTEM_RELATIONSHIP_EDIT,PS_SYSTEM_RELATIONSHIP_ADD]
      new:
        actions:          
          _list:
            credentials: [[PS_SYSTEM_RELATIONSHIP_SHOW,PS_SYSTEM_RELATIONSHIP_EDIT,PS_SYSTEM_RELATIONSHIP_ADD,PS_SYSTEM_RELATIONSHIP_DELETE]]
          _save:
            credentials: [PS_SYSTEM_RELATIONSHIP_ADD]
          _save_and_add:
            credentials: [PS_SYSTEM_RELATIONSHIP_ADD] 
