generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StudentClass
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_student_class
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _delete: {credentials: PS_STUDENT_CLASS_REGISTER_STUDENT}
        _save: {credentials: PS_STUDENT_CLASS_REGISTER_STUDENT}
      fields:  []
      list:    []
      filter:  ~
      form:
        fields:
          start_date_at: {help: Date start studying}
      edit:        
        actions:
          _save: {credentials: PS_STUDENT_CLASS_REGISTER_STUDENT}          
          _cancel: ~
          _delete: {credentials: PS_STUDENT_CLASS_REGISTER_STUDENT}          
      new:
        title:
        actions:
          _save: {credentials: PS_STUDENT_CLASS_REGISTER_STUDENT}
          _cancel: ~
