<html>
    <head>
        <meta charset="utf-8"/>
        <title>Hệ thống quản lý trường mầm non - Preschool Management Software</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
        <script src="https://apis.google.com/js/platform.js" async defer>
		  {lang: 'vi'}
		</script>
    </head>
    <body>
        <h1>API for app mobile</h1>
        <div>
        	<div class="g-page" data-href="//plus.google.com/u/0/107803262317185125286" data-rel="publisher">
				<a href="https://plus.google.com/107803262317185125286" rel="publisher">Google+</a>
			</div>
        </div>
    </body>
</html>
