generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsSemester
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_semester
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        display: [school_year_id,ps_customer_id,ps_workplace_id]
      form:    ~
      edit:    ~
      new:     ~
