editSuccess:
  javascripts: 
    # - /psAdminThemePlugin/js/plugin/tinymce/tinymce.min.js
    # - /psAdminThemePlugin/js/modules/ps_album.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js
newSuccess:
  javascripts:
    # - /psAdminThemePlugin/js/plugin/tinymce/tinymce.min.js
    # - /psAdminThemePlugin/js/modules/ps_album.js
    - /psAdminThemePlugin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js