# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security
default:
  is_secure:   true # Yeu cau toan bo ung dung can phai dang nhap

# quyen cua action
# Hien thi danh sach
index:
  is_secure: true
#  credentials: [[PS_CMS_ARTICLES_FILTER_SCHOOL,PS_CMS_ARTICLES_EDIT,PS_CMS_ARTICLES_LOCK,PS_CMS_ARTICLES_ADD,PS_CMS_ARTICLES_DELETE,PS_CMS_ARTICLES_DETAIL]]   

detail:
  is_secure: true
  credentials: [PS_CMS_ARTICLES_DETAIL]
new:
  is_secure: true
  credentials: [PS_CMS_ARTICLES_ADD]
edit:
  is_secure: true
  credentials: [PS_CMS_ARTICLES_EDIT]

updatePublish:
  is_secure: true
  credentials: [PS_CMS_ARTICLES_EDIT]
  
delete:
  is_secure: true
  credentials: [PS_CMS_ARTICLES_DELETE]