generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FeatureOptionSubject
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_feature_option_subject
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
       _delete: {credentials: PS_STUDENT_SUBJECT_DELETE}
      fields:
        created_at : {date_format: HH:mm dd/MM/yyyy}
        updated_at : {date_format: HH:mm dd/MM/yyyy}
        order_by	: {label: Iorder}
        _tpl_custom/type	: {label: Type}
      list:        
        title: FeatureOptionSubject List "%%feature_name%%"        
        display: [feature_option, _tpl_custom/type,order_by,updated_by,updated_at]
        sort: [order_by,asc]
        table_method: doSelectQuery
        object_actions:
          _delete: ~
        actions:
        batch_actions:
          _updateOrder:
            label: Update Order
            credentials: [PS_STUDENT_SUBJECT_EDIT]
          _delete:
            credentials: [PS_STUDENT_SUBJECT_DELETE]
      filter: 
        display: []
        class: true
      form:    ~
      edit:    ~
      new:     ~
