# You can find more information about this file on the symfony website: dung cho thiet lap man hinh
# http://www.symfony-project.org/reference/1_4/en/08-Security
default:
  is_secure:   true # Yeu cau toan bo ung dung can phai dang nhap

all:
  is_secure: true

# quyen cua action
# Hien thi danh sach
show:
  is_secure: true
  credentials: [[PS_STUDENT_SUBJECT_EDIT,PS_STUDENT_SUBJECT_ADD,PS_STUDENT_SUBJECT_DELETE,PS_STUDENT_SUBJECT_FILTER_SCHOOL]]   

delete:
  is_secure: true
  credentials: [PS_STUDENT_SUBJECT_DELETE]