indexSuccess:
  has_layout:     true
  layout:         layout
  javascripts:
    - /psAdminThemePlugin/js/notification/SmartNotification.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/form_validation.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/framework/bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/i18n.min.js
    - /psAdminThemePlugin/js/plugin/formvalidation/js/language/vi_VN.js    
    - /psAdminThemePlugin/js/plugin/datatables/jquery.dataTables.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.colVis.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.tableTools.min.js
    - /psAdminThemePlugin/js/plugin/datatables/dataTables.bootstrap.min.js
    - /psAdminThemePlugin/js/plugin/datatable-responsive/datatables.responsive.min.js
    - /psAdminThemePlugin/js/js_action_batch.js
    - /psAdminThemePlugin/js/table.js
  stylesheets:
    - /psAdminThemePlugin/css/fix_title_table.css

editSuccess:
  javascripts: 
    - /psAdminThemePlugin/js/modules/ps_feature.js: {position: last}

newSuccess:
  javascripts:
    - /psAdminThemePlugin/js/modules/ps_feature.js: {position: last}