generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PsAllowance
    theme:                 admin1
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ps_allowance
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
#        _detail: {credentials: [PS_HR_SALARY_EDIT,PS_HR_SALARY_DETAIL,PS_HR_SALARY_DELETE]}
        _edit: {credentials: PS_HR_SALARY_EDIT}
        _new: {credentials: PS_HR_SALARY_ADD}
        _delete: {credentials: PS_HR_SALARY_DELETE,confirm: "Are you sure you want to delete this item?"}
      fields:
        is_activated : {label: Status}
        updated_at : {date_format: HH:mm dd-MM-yyyy}
      list:
        title: Allowance List
        max_per_page: 35
        table_method: doSelectQuery
        display: [ps_customer_id,title,allowance_value,note,is_activated,updated_at]
        actions:
          _new: {credentials: PS_HR_SALARY_ADD}
        object_actions:
#          _detail: {credentials: PS_HR_SALARY_DETAIL}
          _edit: {credentials: PS_HR_SALARY_EDIT}
          _delete: {credentials: PS_HR_SALARY_DELETE}
        batch_actions: {}
#         _delete: {credentials: PS_HR_SALARY_DELETE}  
      filter:
        display: [ps_customer_id,title,is_activated]
      form:
        display: [ps_customer_id,title,allowance_value,note,is_activated]
      edit:    ~
      new:     ~